### PR TITLE
Fix/required form attribute LESQ-165

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 2005

- Updates newsletter form

## Issue(s)

Fixes #LESQ-165

## How to test

1. Go to https://deploy-preview-2134--oak-web-application.netlify.thenational.academy/contact-us

## Screenshots

How it used to look (delete if n/a):

Screenshot 2023-12-13 at 16 45 04

How it should now look:

Screenshot 2023-12-13 at 16 44 33

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by JBR90 — CHANGES_REQUESTED** [review]
I think 'required' is a different font - I think we did something similar with the school picker

**Review by JBR90 — APPROVED** [review]
👍

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Though they are labelled by the correct name, it doesn't seem like the checkboxes have the required attribute set

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
The email input doesn't have the text "(required)" in the label anymore!

**Comment by rightsaidjames** [comment]
The label fields for the newsletter signup fields are `aria-hidden="true"` and I have no idea why this might be the case, as it means that, from a screen reader perspective, these fields have no labels. Functionally and visually it all looks correct, and I can see that Jack's comments are addressed by the latest changes.

Screenshot 2023-12-18 at 10 29 05

Screenshot 2023-12-18 at 10 26 53

**Comment by rightsaidjames** [comment]
Update: it seems that the aria-hidden attribute was originally added for a good reason:
https://github.com/oaknational/Oak-Web-Application/blame/fc4c27edd7ea569d3a0b23807a150ee002b61c52/src/components/Input/Input.tsx#L149
https://github.com/oaknational/Oak-Web-Application/pull/880#pullrequestreview-1140337057

So on that basis Kyle has reverted the change and I can discuss this with @jack-skerrett-oak in the new year. My initial suspicion is that the redundant `aria-labelledby` attribute on the label was causing VoiceOver to read the label twice, so the correct fix would have been to remove this redundant attribute rather than adding `aria-hidden` to the label.

**Review by rightsaidjames — APPROVED** [review]

**Pull request merged**
