### PR TITLE
Curric/lot picker UI update CUR-302

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

- Adds text-overflow to Box component
- Truncates span text to prevent overflowing
- Adds margin top to the examboard buttons

## Issue(s)

Fixes #CUR-302

## How to test

1. Go to https://deploy-preview-2034--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Change to mobile view and click on school phase picker 
3. You should see when exam board options wrap 16px spacing on the top
4. Input text truncates instead of spreading over 2 lines

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-10-17 at 16 17 46
Screenshot 2023-10-17 at 16 17 42

How it should now look:
Screenshot 2023-10-17 at 16 16 23
Screenshot 2023-10-17 at 16 16 20

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by HelenHarlow — CHANGES_REQUESTED** [review]
Some very minor spacing updates from me:

- On the school phase buttons, could there be 16px vertical spacing between the buttons when they stack? So it matches the others
- Could the school phase drop down match the width of the component (like how it does on the subject drop down)?
- Could we reduce the spacing between the inputs and horizontal separator line? In Figma this is 12px. (screenshot attached)

image

**Review by rightsaidjames — APPROVED** [review]
All issues fixed, here's some further  screenshots for documentation purposes:
Screenshot 2023-10-19 at 09 18 06
Screenshot 2023-10-19 at 09 18 19
Screenshot 2023-10-19 at 09 18 56
Screenshot 2023-10-19 at 09 19 13
Screenshot 2023-10-19 at 09 19 38
Screenshot 2023-10-19 at 09 20 20
Screenshot 2023-10-19 at 09 20 26

**Review by lioneljingles — APPROVED** [review]
Looks great!

**Pull request merged**
