### PR TITLE
[PUPIL-710] Add content guidance modal and message to sensitive lessons

### PR DESCRIPTION
**Pull request by BTitterington**
## Description

Music year: 2010

- List of changes

Added new content guidance modal and text area to lessons that have content guidance attached.

## Ticket
https://www.notion.so/oaknationalacademy/OWA-Consent-for-isSensitive-lessons-2a03fa79ca56441ebd290a19e6e14763

## Design 
https://www.figma.com/design/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?node-id=5139-30785&m=dev

## How to test

1. Go to https://deploy-preview-2446--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-year-10-aqa/units/poetry-anthology-first-study-155/lessons/analysing-poppies/overview
2. You should see a contents guidance modal with the appropriate warnings.
3. You shouldn't be able to access any of the lesson without clicking "I understand, continue"
4. ESC and clicking the backdrop should not clear the modal.
5. The "Take me home" should take you back to the browse page

## Screenshots

| Current | New |
|----------|----------|
| image | image |

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@BTitterington looks good - although I noticed when viewing in safari on my mac and via browserstack in iPad view the background is not blurred? Any ideas? Works fine with Chrome and Firefox

image

image

**Comment by messmike** [comment]
@BTitterington this is great, thank you. 'Take me home' I think would link to the [pupils landing page/ year select](https://deploy-preview-2446--oak-web-application.netlify.thenational.academy/pupils/beta/years).

**Comment by BTitterington** [comment]
@RBrownsett It seems those browsers need it setup as `-webkit-backdrop-filter`, which is often done automatically by the build, but it hasn't done here. Also when I try to add specifically it I get a typescript error, so I'm going to have to keep looking at this to understand the issue more.

**Comment by BTitterington** [comment]
@messmike I went off the back url that the component already had. I assume that is what's used in the "View all lessons" button on the top left. Are you sure it should go all the way back to landing/year select?

**Comment by BTitterington** [comment]
@messmike Yes it is the same location as "view all lessons", what would you like the wording changed to? "Take me back to lessons" ?

**Comment by messmike** [comment]
> @messmike Yes it is the same location as "view all lessons", what would you like the wording changed to? "Take me back to lessons" ?

Ok great. Yes, that sounds good thanks @BTitterington

**Review by RBrownsett — APPROVED** [review]
Approved - changes made. Testing notes added to Notion ticket

**Review by benprotheroe — APPROVED** [review]

**Pull request merged**
