### PR TITLE
[CUR-180]: added video guide if video data is being passed through to curriculum overview

### PR DESCRIPTION
**Pull request by sonalisin**
## Description

- Update gql query to account for video information if being passed through
- Added video section to overview page

## How to test

1. Go to https://deploy-preview-1969--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-primary/overview
2. Scroll down to the video section
3. You should see a placeholder video
4. Go to any other subject phase combination, the video guide shouldn't be present

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-10-04 at 12 06 57

How it should now look:
Screenshot 2023-10-04 at 14 28 27

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]
LGTM ✅

**Review by HelenHarlow — CHANGES_REQUESTED** [review]
Three small things from me:

- Could we remove the button to ‘View unit sequence’? This was originally there to make sure users didn’t miss it, but we have a ticket in this sprint to switch the unit sequence and overview tabs, so it’s no longer needed (so long as that ticket is still planned to be completed before launch)
- The text link truncates when resized.. I’ve run it by the design team and consensus is that this is fine because the wording is important, but could we also make ‘new curriculum sequence’ an inline link, going to the same post?
- Body copy looks a little small, this should be Body 1 (18px, 28px line height)

**Review by HelenHarlow — APPROVED** [review]
Looks good!

**Review by rightsaidjames — APPROVED** [review]
With the `Read more about our new curriculum` link that truncates on certain breakpoints, is there a way to make this wrap over two lines when needed? My initial thought is that this would require design work, so maybe not.

Other than that, looks good.

**Pull request merged**
