### PR TITLE
feat: add ability to mark up blog posts with footnotes

### PR DESCRIPTION
**Pull request by mcky**
## Description

Enables marking up blog posts with footnotes in the CMS

Some A11Y feedback would be appreciated, specifically how the footnotes themselves should read (currently the extra labelling attributes are just on the <sup>N</sup>s

## How to test

1. Go to the [testing blog post in preview mode](https://deploy-preview-1670--oak-web-application.netlify.thenational.academy/api/preview/blog/some-blog-post?secret=wsJ3DpANkjZQk9z)
2. Search for "footnote", check both work and the backlinks work
3. [Other blog posts](https://deploy-preview-1670--oak-web-application.netlify.thenational.academy/blog/our-strategy-update) should not contain the "references" section

n.b. footnotes can be modified [in the CMS here](https://cms.thenational.academy/desk/webinarsBlogs;blogPosts;2ed3149d-8c7d-41cb-9123-12ff405ff979)

## Screenshots
Inline:
CleanShot 2023-06-01 at 12 55 19

The end of the blog post:
CleanShot 2023-06-01 at 12 55 11

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
    Attempted to mark up the footnotes as best I could for A11Y, but open to feedback
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by jack-skerrett-oak — COMMENTED** [review]
It's not the end of the world so not requesting changes. When navigating to the references at the bottom of a page from a reference, you lose keyboard focus, you have to tab again to find the link that you have been navigated to. 

i think the feel of having the reference be read out as a link after the information is fine, no issues there. 

https://github.com/oaknational/Oak-Web-Application/assets/102532470/3d32c1f4-f530-4b6b-bc1d-09551589b522

**Review by JBR90 — APPROVED** [review]
Looks good and works as described. My only thought was should the backlinks open in a new tab?

**Comment by mcky** [comment]
> Looks good and works as described. My only thought was should the backlinks open in a new tab?

@JBR90 The backlinks are to back within the same page so they shouldn't be in a new tab. Do you mean the reference links themselves? If there's a general OWA/homesite policy of opening external links in new tabs I can make it so

> When navigating to the references at the bottom of a page from a reference, you lose keyboard focus, you have to tab again to find the link that you have been navigated to.

@jack-skerrett-oak I'll defer to you on this if you feel strongly about it, but as far as I understand that's normal browser behaviour (you have navigated within a page, focus is reset but begins from the point you've navigated to) so I'm hesitant to change it.
If it's about visibility rather than keyboard navigation, we could do is something like wikipedia in which the active citation is highlighted
CleanShot 2023-06-19 at 11 21 17@2x

**Comment by mcky** [comment]
@JBR90 @jack-skerrett-oak I'll merge this as-is but depending on your feedback to the above I'll make a follow-up, as I've left these PRs to stagnate for a while

**Comment by jack-skerrett-oak** [comment]
> > Looks good and works as described. My only thought was should the backlinks open in a new tab?
> 
> @JBR90 The backlinks are to back within the same page so they shouldn't be in a new tab. Do you mean the reference links themselves? If there's a general OWA/homesite policy of opening external links in new tabs I can make it so
> 
> > When navigating to the references at the bottom of a page from a reference, you lose keyboard focus, you have to tab again to find the link that you have been navigated to.
> 
> @jack-skerrett-oak I'll defer to you on this if you feel strongly about it, but as far as I understand that's normal browser behaviour (you have navigated within a page, focus is reset but begins from the point you've navigated to) so I'm hesitant to change it. If it's about visibility rather than keyboard navigation, we could do is something like wikipedia in which the active citation is highlighted CleanShot 2023-06-19 at 11 21 17@2x

@mcky happy for it to be a thing that happens. I would be careful to avoid introducing any styling changes, might need to set up some workflow with design if your work does start to require designs

**Pull request merged**
