### PR TITLE
New lot picker epic

### PR DESCRIPTION
**Pull request by orangemug**
## Description
Collection of PRs for the new lot picker designs

 - https://github.com/oaknational/Oak-Web-Application/pull/2767
 - https://github.com/oaknational/Oak-Web-Application/pull/2751
 - https://github.com/oaknational/Oak-Web-Application/pull/2776

## Issue(s)

`CUR-783`, `CUR-784` & `CUR-857` 

## Test URL:

https://deploy-preview-2744--oak-web-application.netlify.thenational.academy/teachers/curriculum

### CODE REVIEW

**Comment by orangemug** [comment]
@sonalisin a few issues I spotted, lets get others to review also and we'll fix all the issues in one batch 

Screenshot 2024-09-12 at 16 44 31

**Review by HelenHarlow — COMMENTED** [review]
Looks so good! A few things I spotted:

• Is it possible to make it so that when a user chooses an option, the focus is moved to the next part of the lot picker? (e.g. once you select a subject, the next menu will open. Or when a school phase is chosen, focus is moved to the view button). See current lot picker behaviour for reference

• When I first click on the school phase (mobile only), it looks like this until the mouse is moved from that section. Not sure if that’s just for me? The school phase menu is also slightly misaligned on the left
Screenshot 2024-09-12 at 17 02 15

• The hover state for the selected button should be just an underline on the text with a black background still (see the filters on the search page as an example)

**Review by rightsaidjames — APPROVED** [review]
Looks good to me from a functional perspective, so it's just @HelenHarlow's outstanding changes I think and then we're good to go, right @orangemug?

**Comment by orangemug** [comment]
Current list of fixes

 - ~~Invalid border radius~~
 - ~~Square edge~~
 - ~~Slightly indented~~
 - ~~The hover state for the selected button should be just an underline on the text with a black background still (see the filters on the search page as an example)~~
 - When I first click on the school phase (mobile only), it looks like this until the mouse is moved from that section. Not sure if that’s just for me? The school phase menu is also slightly misaligned on the left
 - Is it possible to make it so that when a user chooses an option, the focus is moved to the next part of the lot picker? (e.g. once you select a subject, the next menu will open. Or when a school phase is chosen, focus is moved to the view button). See current lot picker behaviour for reference

**Pull request merged**
