### PR TITLE
Curric/school picker bug fix CUR-255

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

- Add promotional tag to the subjects drop down 
- Refactors some of the components to prevent view from being truncated
- Adds some styling for Mobile phone views 

## Issue(s)

Fixes #CUR-255

## How to test

1. Go to https://deploy-preview-1897--oak-web-application.netlify.thenational.academy/beta/teachers/curriculum
2. Click on School Phase Picker
3. Try at variety if view ports 

## Screenshots

How it used to look:
Screenshot 2023-09-12 at 14 22 10
Screenshot 2023-09-12 at 14 22 34

How it should now look:
Screenshot 2023-09-12 at 14 12 27
Screenshot 2023-09-12 at 14 12 43
Screenshot 2023-09-12 at 14 18 05

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by rightsaidjames — CHANGES_REQUESTED** [review]
Looks a lot better!

However the grey text color in the 'form fields' of the picker does not pass colour contrast - I suggest reverting it back to black.
Screenshot 2023-09-12 at 16 53 48
Screenshot 2023-09-12 at 17 00 08

**Comment by k-huggs** [comment]
> Looks a lot better!
> 
> However the grey text color in the 'form fields' of the picker does not pass colour contrast - I suggest reverting it back to black. Screenshot 2023-09-12 at 16 53 48 Screenshot 2023-09-12 at 17 00 08

Changed to black ✅

**Review by HelenHarlow — CHANGES_REQUESTED** [review]
This looks so much better! A few small changes from me:
1. Is it possible to make the divider lines (between subject & school phase, and additionally on mobile the also the line above the CTA) grey? In the design this is Grey 2 (CACACA)
2. Could the title in the first drop down be ‘Latest resources’ rather than ‘Latest resources for 2023/24’? To avoid duplication with the subcopy underneath
3. For the school phase drop down, on tablet screens where the tiles stack vertically, could we add some padding between? In the designs this is 16px
4. On those school phase tiles, if poss could we update the text styles to match design? The first line (Primary/Secondary) is Heading 7, and the Key stage & Years are Body 2

**Comment by rightsaidjames** [comment]
Grey text colour has been changed back to black 👍 

From @HelenHarlow's comments, it looks like points 1 and 2 are fixed but for 3 we still need some vertical padding added for the phase options when they are vertically stacked.
Screenshot 2023-09-13 at 09 13 24
a8-d720-4667-9074-1916b6131b63">

Additionally point 4 is still outstanding, the phase options should have text styling that looks like this, where only the phase (and not the key stage and years) are bolded:
Screenshot 2023-09-13 at 09 30 48

**Review by rightsaidjames — APPROVED** [review]
Given that point 4 of Helen's feedback is a Won't Fix/Can't Fix for now, I think we're good to go. The vertical padding for the stacking phase options looks good, and I can see that Lionel's changes have been incorporated.
Screenshot 2023-09-13 at 12 36 48
Screenshot 2023-09-13 at 12 37 10
Screenshot 2023-09-13 at 12 37 25
Screenshot 2023-09-13 at 12 37 35

**Review by HelenHarlow — APPROVED** [review]
Looks good ! I'll let you know as soon as I have the finalised copy for the link out to the legacy downloads

**Pull request merged**
