### PR TITLE
Feat/pupil 681/style subject listing page

### PR DESCRIPTION
**Pull request by kimon-satan**
## Description

When I view the SubjectListingPage,
I want to see all the oak styles and components
So that the UX is high quality.

## How to test

1. Go to https://deploy-preview-2419--oak-web-application.netlify.thenational.academy/pupils/beta/years/year-3/subjects
2. Go to https://deploy-preview-2419--oak-web-application.netlify.thenational.academy/pupils/beta/years/year-10/subjects

## Screenshots

How it used to look (delete if n/a):
image

How it should now look:
image

## ACs

- [x]  page matches designs
- [x]  screen readable
- [x]  keyboard navigable
- [x] displays correct subjects (legacy only)
- [x] mobile , tablet, desktop

### CODE REVIEW

**Comment by messmike** [comment]
cheers @kimon-satan I think the only thing to update is the inner padding (top/ bottom) of the container to `inner-padding-xl7` for desktop/ tablet and `inner-padding-xl5` for mobile:
Screenshot 2024-05-13 at 4 55 03 pm
Screenshot 2024-05-13 at 4 54 38 pm

**Comment by messmike** [comment]
> > cheers @kimon-satan I think the only thing to update is the inner padding (top/ bottom) of the container to `inner-padding-xl7` for desktop/ tablet and `inner-padding-xl5` for mobile: Screenshot 2024-05-13 at 4 55 03 pm Screenshot 2024-05-13 at 4 54 38 pm
> 
> > cheers @kimon-satan I think the only thing to update is the inner padding (top/ bottom) of the container to `inner-padding-xl7` for desktop/ tablet and `inner-padding-xl5` for mobile: Screenshot 2024-05-13 at 4 55 03 pm Screenshot 2024-05-13 at 4 54 38 pm
> 
> can we do these in separate ticket. We're still behind on meeting our sprint goals.

[https://www.notion.so/oaknationalacademy/OWA-Subject-Listing-Page-container-padding-9de816a83cd84e918c29e3c025f4e2ec?pvs=4](https://www.notion.so/oaknationalacademy/OWA-Subject-Listing-Page-container-padding-9de816a83cd84e918c29e3c025f4e2ec?pvs=4)

**Review by messmike — APPROVED** [review]
Added another ticket to the backlog for the padding update: [https://www.notion.so/oaknationalacademy/OWA-Subject-Listing-Page-container-padding-9de816a83cd84e918c29e3c025f4e2ec?pvs=4](https://www.notion.so/oaknationalacademy/OWA-Subject-Listing-Page-container-padding-9de816a83cd84e918c29e3c025f4e2ec?pvs=4)

**Review by RBrownsett — APPROVED** [review]
1. Tested across multiple browsers and devices (details on Notion ticket)
2. Tested accessibility (accessibility insights report attached to ticket)
3. Tested each year displays the correct subjects
4. Tested units and lessons flow
5. Tested programme page is displayed for subjects with programmes (maths/combined science)

**Review by benprotheroe — APPROVED** [review]

**Pull request merged**
