### PR TITLE
LESQ-1002: Onboarding page layout

### PR DESCRIPTION
**Pull request by carlmw**
## Description

Music year: 1970

## Issue(s)

Fixes
* Header and footer being cropped when page scrolls
* Makes border radii match on both the registration and onboarding pages
* Makes the width of the cards on the registration and onboarding pages the same (400px)
* Makes padding of the cards on registration and onboarding pages match (40px)

👋🏻 I wasn't able to get the padding of the registration pages to line up perfectly on the left+right with onboarding on mobile owing to some internal CSS within Clerk's components that would be very messy to override — tbh I don't think it's all that noticeable unless you lay screenshots of both pages on top of each other.

Adds
* A heading and illustration to the onboarding pages

Doesn't
* Change anything inside the sign-up/in form. I think there is quite a bit more work we could do in there but it's outside the scope of this ticket.

## How to test

1. While signed out
2. Go to https://deploy-preview-2735--oak-web-application.netlify.thenational.academy/onboarding
3. 👀 admire the sign-in and sign-up pages
4. Sign-in
5. 👁️ ogle the onboarding pages
6. Both sets should have the same width, border treatments and responsiveness

### Desktop
localhost_3000_sign-in (1)
localhost_3000_onboarding___clerk_handshake=eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18yVTNsZ0dWMU5jNmtCRXZsRWdaejcyNzFPS2siLCJ0eXAiOiJKV1QifQ eyJoYW5kc2hha2UiOlsiX19jbGllbnRfdWF0PTsgUGF0aD0vOyBFeHBpcmVzPVRodSwgMDEgS

### Tablet
localhost_3000_sign-in(iPad Air)
localhost_3000_onboarding(iPad Air)

## Mobile
localhost_3000_sign-in(iPhone 12 Pro)
localhost_3000_onboarding(iPhone 12 Pro)

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by carlmw** [comment]
> Nicee 🤌 one thing bugging me is the role selection page spacing has been a bit wonky for a while, is fixing that out of this ticket's scope? (I also think tablet size should use desktop layout, but will defer to Monika's judgement on that 😇)

@njblore which spacing do you mean?

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
A few changes from me:

- [ ] Can we make sure all text is using the text-prmary colour token? Some of it is using just #00000 which is different to Oak black #222222
- [ ] Should is say 'Select from **the** dropdown' rather than ' Select from dropdown' – can we check with an English speaker it's my weak point
- [ ] On manual school entry it should say: 'Enter school’s details'
- [ ] The manual 'select your school box' – can we make the spacing between the input fields smaller e.g. 24px space-between-m? 
- [ ] Was the back button part of this ticket? 
- [ ] Can we use heading-6 style (20px) for all the questions?
- [ ] When selecting other in the role selector the input field overlaps the text (see screenshot attached), can we add some spacing there
Screenshot 2024-08-27 at 12 03 26
- [ ] The continue button should only be disabled once the user tries to click on it and didn't fill in mandatory fields

**Comment by carlmw** [comment]
> A few changes from me:
> 
> * [ ]  Can we make sure all text is using the text-prmary colour token? Some of it is using just #00000 which is different to Oak black #222222
> * [ ]  Should is say 'Select from **the** dropdown' rather than ' Select from dropdown' – can we check with an English speaker it's my weak point
> * [ ]  On manual school entry it should say: 'Enter school’s details'
> * [ ]  The manual 'select your school box' – can we make the spacing between the input fields smaller e.g. 24px space-between-m?
> * [ ]  Was the back button part of this ticket?
> * [ ]  Can we use heading-6 style (20px) for all the questions?
> * [ ]  When selecting other in the role selector the input field overlaps the text (see screenshot attached), can we add some spacing there
>   Screenshot 2024-08-27 at 12 03 26
> * [ ]  The continue button should only be disabled once the user tries to click on it and didn't fill in mandatory fields

@Monika-Koziol i'll take care of as much of this as I can, but this reads like a snagging list for all the tickets that came before. If I find any of these prove complicated i'll split them off into another ticket.

**Comment by rightsaidjames** [comment]
>  Should it say 'Select from the dropdown' rather than ' Select from dropdown' – can we check with an English speaker it's my weak point

I think 'Select from dropdown' is fine in this context, it's fairly typical to leave out 'the' in this context (e.g. when giving instructions/options on a form).

Everything in the initial scope looks fine to me, so I guess it's just Monika's snaglist.

**Comment by njblore** [comment]
@carlmw for the spacing I was referring to what Monika said about the 'other' input box and also there is no padding around the top of the form on this page:

**Comment by carlmw** [comment]
@Monika-Koziol i've done most of the list. I think the only thing that requires a bit more work is correcting the behaviour of the Continue button. I think there might already be a ticket for adding the back button (though the browser back button works!)

- [x] Can we make sure all text is using the text-prmary colour token? Some of it is using just #00000 which is different to Oak black #222222
- [ ] ~Should is say 'Select from the dropdown' rather than ' Select from dropdown' – can we check with an English speaker it's my weak point~ I think we 
- [x]  On manual school entry it should say: 'Enter school’s details'
- [ ]  The manual 'select your school box' – can we make the spacing between the input fields smaller e.g. 24px space-between-m?

☝🏻  I had some trouble with this, i've done my best but the error state throws things off a bit — I don't want to touch the underlying component because it could trigger some side-effects elsewhere in OWA. 

- [ ]  ~Was the back button part of this ticket?~ No
- [x]  Can we use heading-6 style (20px) for all the questions?
- [x]  When selecting other in the role selector the input field overlaps the text (see screenshot attached), can we add some spacing there
- [ ]  The continue button should only be disabled once the user tries to click on it and didn't fill in mandatory fields

☝🏻  this proved tricky, we can split this out into a bug ticket.

**Comment by Monika-Koziol** [comment]
@carlmw thanks for the changes. Don't worry about this one:
`The manual 'select your school box' – can we make the spacing between the input fields smaller e.g. 24px space-between-m?` it's not a biggie. 
Maybe we can write another ticket for the continue button?

**Review by Monika-Koziol — APPROVED** [review]

**Pull request merged**
