### PR TITLE
Feat/host mathjax package json LESQ-386

### PR DESCRIPTION
**Pull request by JBR90**
## Description

- Adds MathJax node package
- Adds copy-webpack-plugin node package
- Update next.config (Copies mathjax from node to public)
- Updates provider to point to public folder rather than cdn (default)

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2007--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation/units/surds/lessons/accuracy-of-final-answers#exit-quiz
You should see mathjax in the quizzes

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by njblore** [comment]
Did we have any way of reproducing the error to verify it's fixed? I'm seeing this error in the console, may be something different/unrelated: 
Screenshot 2023-10-11 at 10 42 41

**Review by kimon-satan — CHANGES_REQUESTED** [review]
surely there's an npm or minified version ?

**Review by mantagen — COMMENTED** [review]
Sorry to overcrowd with another response.

Would it be possible to do what you've done (webpack copy etc), but to gitignore the public/mathjax folder?

**Review by kimon-satan — APPROVED** [review]

**Comment by JBR90** [comment]
> surely there's an npm or minified version ?

Not atm, fingers crossed for Mathjax 4

**Review by jack-skerrett-oak — COMMENTED** [review]
Mathjax is still rendered, not sure how else I can help here :D

**Review by jack-skerrett-oak — APPROVED** [review]

**Pull request merged**
