### PR TITLE
style: update input school dropdown styles

### PR DESCRIPTION
**Pull request by JBR90**
## Description

**Job Story:**

When *the user downloads content*, I want to *have a user friendly school picker*, so that *it’s easy to use*.

## Acceptance Criteria:

- [x]  Label font: use Heading 7 regular style for main part and Heading 7 light for the required/optional copy
- [x]  Yellow label paddings: top/bottom=4px, left/right=8px
- [x]  Yellow box: change transform setting to: rotate(-2deg) translateY(-12px) translateX(8px) (so the box moves up and to the right)
- [x]  Input field: change height from 44px to 60px,
- [x]  Inner field text paddings: 16px all round, margin 0
- [x]  Dropdown-item: change hover state to grey background and underline text (see figma)
- [x]  Change typed in letters colour to blue and underline them (see figma)
- [x]  Check the newsletter form on home page has the same input styling

https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=209-8451&mode=design

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2044--oak-web-application.netlify.thenational.academy
2. 1. Go to https://deploy-preview-2044--oak-web-application.netlify.thenational.academy/teachers/programmes/citizenship-secondary-ks4-l/units/how-well-does-the-media-hold-those-in-power-to-account-63c4/lessons/what-is-the-role-of-the-media-in-a-democracy-cmw32c/downloads?preselected=slide+deck

Homepage - news letter form / search input
Downloads page - school picker / inputs

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]
LGTM ✅

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
Couple of small changes based on seeing it live on the page and changing some of the acceptance criteria. Sorry 
- [x] Yellow box change change of of the values of transform translate Y to -16 
- [ ] Padding around inner text 16,20,16,16 ( I’d like us to only use multiple of 4 if possible) 
- [ ] In the expanded view: is is possible to have a line underneath the top input? See screenshot attached. Just it looks a bit odd when there are many items and user starts scrolling 
- [ ] Is the font size for the dropdown items on homepage the same? It looks a bit smaller but I wasn't sure

Screenshot 2023-10-25 at 09 17 11

**Review by Monika-Koziol — APPROVED** [review]
Looking good.

**Pull request merged**
