### PR TITLE
feat: remove the isSensitive units and lessons from pupil browse

### PR DESCRIPTION
**Pull request by BTitterington**
## Description

Music year: 2005

Removed any units or lessons with the isSensitive field set to `true`.
This has been done within getStaticProps so that it happens server side.

## How to test

1. Go to https://deploy-preview-2447--oak-web-application.netlify.thenational.academy/pupils/beta/programmes/rshe-pshe-secondary-year-10-l/units
2. You should see 4 units (before there were 6)
3. Go to https://deploy-preview-2447--oak-web-application.netlify.thenational.academy/pupils/beta/programmes/rshe-pshe-secondary-year-10-l/units/online-and-media-dangers-of-viewing-explicit-material-6a7c/lessons
4. You should see 4 lessons (before there were 5)

## Screenshots

| Current | New |
|----------|----------|
| image | image |

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by benprotheroe — APPROVED** [review]
looks good

**Comment by RBrownsett** [comment]
@BTitterington looks good, units and lessons have been removed where is_sensitive is set to true. Just need to check the lesson count is correct - e.g. :
image

**Review by RBrownsett — APPROVED** [review]
Approved - lesson count will be covered in a follow on ticket

**Pull request merged**
