### PR TITLE
PUPIL-582: Add MathJax support to the pupil quiz

### PR DESCRIPTION
**Pull request by carlmw**
## Description

This ticket implements mathjax support in pupil lessons.

Richard can confirm the functionality.

@JBR90 I'd appreciate if you could do a code review as I think you have a bit of experience with mathjax and I'm also the only dev in my squad for a couple of weeks.  

## How to test

1. Go to https://deploy-preview-2348--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/simplifying-before-multiplying-with-multiple-expressions/exit-quiz
2. Goto question 4
3. You should be able to drag and drop mathjax items

_
1. Go to https://deploy-preview-2348--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/highest-common-factor-with-algebraic-terms/starter-quiz
2. The x & y values should look algebraic, right clicking them will show mathjax dialog.

_
1. Go to https://deploy-preview-2348--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/simplifying-before-multiplying-with-multiple-expressions/starter-quiz
2. Get question 5 wrong, the incorrect information at the bottom of the page should also show text in mathjax format.

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by benprotheroe** [comment]
@carlmw  I couldnt get this to work on match questions; i had some success by following [this advise](https://medium.com/@axcodes/how-to-use-mathjax-in-next-js-2ee53ba6a695) in oak-components but it was glitchy I must be something to do with when you the mathjax.js file from the linked tutorial. I tried implementing it in OWA and it has no effect on the maths when the draggable item was being dragged.

**Comment by RBrownsett** [comment]
@BTitterington looking good - match questions work well with different browsers. The only issue I have seen is making the Mathjax appearing when we display a correct answer (see screenshot)

image

**Comment by BTitterington** [comment]
> @BTitterington looking good - match questions work well with different browsers. The only issue I have seen is making the Mathjax appearing when we display a correct answer (see screenshot)
> 
> image

Cool, should be able to pick that up and create a proper PR later today or early tomorrow. Thanks.

**Review by RBrownsett — APPROVED** [review]
Correct answer element is now rendered correctly using Mathjax.

**Review by njblore — COMMENTED** [review]
Looks good to me but should point out that we get a lot of [errors in production from mathjax](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/65f08c6111d8a60008c6eef5?filters[event.unhandled]=true&filters[event.since]=30d&filters[app.release_stage]=production&filters[search]=mathjax) that we haven't been able to get to the bottom of, so in order to reduce these we're only using the provider/wrapper for content that contains mathjax syntax in the teacher journey. 
It would be interesting to see if pupils isn't affected by the same errors, but I suspect it will be, so might be worth getting ahead of and doing the same here

**Comment by BTitterington** [comment]
> Looks good to me but should point out that we get a lot of [errors in production from mathjax](https://app.bugsnag.com/oak-national-academy/oak-web-application/errors/65f08c6111d8a60008c6eef5?filters%5Bevent.unhandled%5D=true&filters%5Bevent.since%5D=30d&filters%5Bapp.release_stage%5D=production&filters%5Bsearch%5D=mathjax) that we haven't been able to get to the bottom of, so in order to reduce these we're only using the provider/wrapper for content that contains mathjax syntax in the teacher journey. It would be interesting to see if pupils isn't affected by the same errors, but I suspect it will be, so might be worth getting ahead of and doing the same here

@njblore I took a look and I think there is a bit of work to make the `hasLessonMathJax` helper function work with the data I have on the pupil side. After speaking with @aakeshp we're going to create a seperate ticket to narrow down the wrapper usage to mathjax lessons and adjust it's priority based on monitoring errors around it.

**Review by njblore — APPROVED** [review]

**Pull request merged**
