### PR TITLE
[ENG-132] feat: enable A/B testing of landing pages via the CMS

### PR DESCRIPTION
**Pull request by mcky**
## Description
- Landing pages are now entirely server rendered (no static, no ISR). This is to avoid a bad UX where the control variant is shown until the client-side JS takes over and then a variant is re-rendered, and because we can only get the users cookies via SSR
- If a landing page with an experiment is encountered, the user will be redirected to one of the variants. These were initially all rendered on the same URL, but it was swapped to redirecting because of complications with hubspot tracking
- Users that have previously consented and therefor have a posthog cookie will be shown the variant posthog decides, entirely anonymous users will be sent to a randomly selected control or variant page
- Landing pages without experiments should be exactly the same, just SSR'd

Known issue: Currently if a user has no cookies set they will see a random variant. If they then accept cookies and return to the experiment page, they will potentially see a different variant. This is a tradeoff agreed with Simon H.

TODO: Unset the `SANITY_DATASET_TAG`, which is currently set to `ab-test` for this branch specifically

## Issue(s)

Fixes #

## How to test
As an identified user:
1. Go to the [deploy preview homepage](https://deploy-preview-1766--oak-web-application.netlify.thenational.academy)
2. Accept cookies
3. Go to the A/B tested landing page[/lp/ab-test](https://deploy-preview-1766--oak-web-application.netlify.thenational.academylp/ab-test)
4. You should be redirected to a variant page. Each time you return to the above link you're redirected to the same variant.

As an anonymous user
1. Clear cookies & site data
2. Go to the A/B tested landing page[/lp/ab-test](https://deploy-preview-1766--oak-web-application.netlify.thenational.academylp/ab-test)
3. Do not accept cookies
4. Each time you return to the above link you should be redirected to a random variant

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [ ] ~Considered impact on accessibility~
- [ ] ~Design sign-off~
- [x] Approved by product owner

### CODE REVIEW

**Comment by jimCresswell** [comment]
I guess it's fine for the landing pages to be SSR, as long as everyone is clear that the curriculum pages remain static for performance reasons (just writing that for posterity).

Is there are way to control the variant for end-to-end testing purposes, e.g. Pa11yCI, Percy?

**Review by jimCresswell — APPROVED** [review]
LGTM, testing issues discussed and agreed it won't be an issue. Please get @mantagen to take a look as well.

**Review by jack-skerrett-oak — APPROVED** [review]

**Review by mantagen — APPROVED** [review]
LGTM

**Pull request merged**
