### PR TITLE
Feat/pupil 901/quiz result match

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 1955

- List of changes

### Job Story

**When** a question has type “match”,
**I want to a component** OakQuizMatchResult
**So that the results of the question can be displayed**.

## Issue(s)

Fixes #

## How to test

1. Go to [https://deploy-preview-2662--oak-web-application.netlify.thenational.academy](https://deploy-preview-2662--owa-storybook.netlify.thenational.academy/?path=/story/components-pupilcomponents-quizresultmatch--correct-match)
2. Click on correct and incorrect answers
3. You should see correct style and copy

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by messmike** [comment]
Looks good, the only thing that would be good is to align the text to the left (start) on mobile:
Screenshot 2024-08-05 at 10 05 38 am
Screenshot 2024-08-05 at 10 07 38 am

I just want to check too that the items would span across multiple lines when the width is exceeded? 
Screenshot 2024-08-05 at 10 08 31 am

**Comment by RBrownsett** [comment]
@benprotheroe I imagine the alignment ticket that @kimon-satan is working on fix some of the issues we are seeing in mobile view? https://github.com/oaknational/oak-components/pull/264

**Review by kimon-satan — APPROVED** [review]

**Comment by kimon-satan** [comment]
> @benprotheroe I imagine the alignment ticket that @kimon-satan is working on fix some of the issues we are seeing in mobile view? [oaknational/oak-components#264](https://github.com/oaknational/oak-components/pull/264)

Yep OakComponents just needs bumping here and all will be well in the state of denmark

**Comment by benprotheroe** [comment]
all bumped, good to check!

**Review by messmike — APPROVED** [review]

**Pull request merged**
