### PR TITLE
LESQ-956: updates PostFootnates component and removes additional provider

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: {owa_music_year}

- Amends the PostFootnotes component to utilise OakComponent Lib
- Wraps label so it doesn't extend out of parental DIV
- Amends test file

## Issue(s)

Fixes #LESQ-956

## How to test

1. Go to https://deploy-preview-2620--oak-web-application.netlify.thenational.academy
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look:
https://github.com/user-attachments/assets/b8afebe6-6585-4521-bf5b-58b25b8e47ec

https://github.com/user-attachments/assets/2675d15b-5a71-4540-b9f9-f2967495f6e7

How it should look:
https://github.com/user-attachments/assets/11b05116-f5a9-4c5e-b89e-5abcd80ef27b

https://github.com/user-attachments/assets/472e9f0f-715a-49be-b808-1191d365bb58

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [x] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Comment by RBrownsett** [comment]
@k-huggs functionally no issues - I have tested this across different browsers and devices and it wraps correctly.

My only question was should test.only be used? Will this only run that test in the test file?

**Comment by k-huggs** [comment]
> @k-huggs functionally no issues - I have tested this across different browsers and devices and it wraps correctly.
> 
> My only question was should test.only be used? Will this only run that test in the test file?

Accidentally left in, good spot! Removed ✅

**Review by RBrownsett — APPROVED** [review]
Approved - example device in Browserstack :

image

**Review by carlmw — APPROVED** [review]

**Pull request merged**
