### PR TITLE
Lesq 751   radio buttons in fieldset with legend - LESQ-751

### PR DESCRIPTION
**Pull request by JBR90**
## Description

Music year: 1960

- Add fieldset and legend to checkbox group for resources (downloads not share)
- Adds fieldset and legend to school picker and 'school not listed' checkbox 

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2489--oak-web-application.netlify.thenational.academy
download : downloads lesson resources group should be read out 
school picker and checkbox: school details group school be read out.

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
The changes here haven't really improved anything on the downloads forms. Looking at the ticket from the a11y audit, they have attached a screen shot specifically linked to the resource selection part of the form rather than the user input section. 

I'm not sure how the fieldset legend markup will help that section so probably worth a try given that is the feedback that was given (and we have to trust them somewhat), but I don't think there is any point (sadly) merging what has been done.

**Comment by JBR90** [comment]
> The changes here haven't really improved anything on the downloads forms. Looking at the ticket from the a11y audit, they have attached a screen shot specifically linked to the resource selection part of the form rather than the user input section.
> 
Feels like school picker and radio button comes under related 'Questions with related answers' so though i should add it as i was there.
https://accessibility.blog.gov.uk/2016/07/22/using-the-fieldset-and-legend-elements/

> I'm not sure how the fieldset legend markup will help that section so probably worth a try given that is the feedback that was given (and we have to trust them somewhat), but I don't think there is any point (sadly) merging what has been done.

There are subtle improvements, the screen reader now states 'group' for the resource checkboxes and the checkbox / school picker combo. The legend is only read out and not visible on the site, this now states `Select resources to download` for checkboxes and 'school details' on the form for the school picker and radio group. This copy could be improved maybe, but it seems like this is worth merging to me.

**Review by jack-skerrett-oak — COMMENTED** [review]
Completely blundered that last review. Things are better than I thought :D 

One question on the fieldset for the school picker section. It describes "school details, group" which makes sense because there is the school combobox and checkbox, but then it also describes "my school isn't listed, group" which doesn't really make sense. I can't see why the code thinks that though... 
Screenshot 2024-06-11 at 14 38 48 1
Screenshot 2024-06-11 at 14 39 02

**Review by jack-skerrett-oak — APPROVED** [review]
That's gotten rid of it, have fun on your holidays :)

**Pull request merged**
