### PR TITLE
LESQ-1091: show new only filter on search page

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 1985

- Adds UI to search page to filter 
- Updates test file
- Updates query when selected to be `curriculum=new`

## Issue(s)

Fixes #LESQ-1091

## How to test

1. Go to https://deploy-preview-2857--oak-web-application.netlify.thenational.academy
2. Use search
3. When the curriculum new button is selected, `curriculum=new` added to the url and all search items should be non-legacy. 

## Screenshots

How it should now look:

https://github.com/user-attachments/assets/2bef5db5-52c0-4454-a746-a6fe2ed7ee2c

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
A few small changes:

- [ ] can we add a grey divider line at the bottom as per other filter groups?
- [ ] can we change 'New' font size to body-3-bold same as other tags on the page
- [ ] seeing it live I think let us add a bit bigger spacing between the tag and the extra copy – 16px (spac-betweens) sorry a change of mind on my side.

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
Apologies, I wasn't clear enough about the spacing, hope this makes sense: 
- [ ] space between 'show new only' filter and New & subcopy to be 16px (see attached screenshot)
- [ ] space between 'New tag' and subcopy change back to 4px/

Screenshot 2024-10-08 at 15 44 45

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
[ ] I know you have just done a design tweak, but now the "New" flag seems a bit squashed! 
Screenshot 2024-10-09 at 09 44 30
[ ] Is there a reason why it isn't shown in the list of active filters? I can't see anything in spec anywhere but don't want to assume given how removed I am

**Comment by k-huggs** [comment]
> [ ] I know you have just done a design tweak, but now the "New" flag seems a bit squashed! Screenshot 2024-10-09 at 09 44 30 [ ] Is there a reason why it isn't shown in the list of active filters? I can't see anything in spec anywhere but don't want to assume given how removed I am

Active filters and sizing should now be fixed ✅

**Comment by k-huggs** [comment]
> Apologies, I wasn't clear enough about the spacing, hope this makes sense:
> 
> * [ ]  space between 'show new only' filter and New & subcopy to be 16px (see attached screenshot)
> * [ ]  space between 'New tag' and subcopy change back to 4px/
> 
> Screenshot 2024-10-08 at 15 44 45

Amended ✅

**Review by jack-skerrett-oak — APPROVED** [review]
Looks to be doing what it should be doing :)

**Pull request merged**
