### PR TITLE
fix(section): make view all lessons button work

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 2013

- List of changes

on the lesson page for the browse journey the "view all lessons" button takes you back to the the lesson listing page

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2427--oak-web-application.netlify.thenational.academy/pupils/beta/programmes/maths-secondary-year-11-higher-l/units/circle-theorems-1-1521/lessons
2. Click on a lesson 
3. You should be able to nav back to this page from lesson

### Job Story

**When** I am on a pupil lesson,
**I want to the back button to navigate back to the previous page**
**So that when its the user journey pupuls can go back to the lesson listing page**.

### Implementation details

- Use the unit and programme slug to determine the href
- note that for users who have arrived here from the classroom the link stays the same and take you back to the classoom

```jsx
https://www.thenational.academy/pupils/l/cooking-and-nutrition-preparing-fruit-and-vegetables-2007/lessons/introduction-exploring-delicious-fruits-and-vegetables-crvk4t/overview
```

- link back to beta journey if user has come from beta journey

Untitled

### Acceptance criteria

- [ ]  back button is enabled and navigates back to unit page

### CODE REVIEW

**Review by kimon-satan — APPROVED** [review]

**Comment by RBrownsett** [comment]
@benprotheroe just checking - where did we land with canonical lesson links? When I go to https://deploy-preview-2427--oak-web-application.netlify.thenational.academy/pupils/lessons/atoms-elements-and-compounds-h3hasv/overview and click 'view all lessons' it goes to the classroom unit page https://classroom.thenational.academy/units/atomic-structure-and-the-periodic-table-u68nqqc

@messmike mocked up some designs on what it would do (back to the year page)

**Comment by messmike** [comment]
> @benprotheroe just checking - where did we land with canonical lesson links? When I go to https://deploy-preview-2427--oak-web-application.netlify.thenational.academy/pupils/lessons/atoms-elements-and-compounds-h3hasv/overview and click 'view all lessons' it goes to the classroom unit page https://classroom.thenational.academy/units/atomic-structure-and-the-periodic-table-u68nqqc
> 
> @messmike mocked up some designs on what it would do (back to the year page)

Here is the mock for this @benprotheroe [https://www.figma.com/design/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?m=dev&node-id=5175%3A42269](https://www.figma.com/design/zqpeecgzMGKRli2gUdJOLp/Pupil-Browse?m=dev&node-id=5175%3A42269)

**Comment by benprotheroe** [comment]
> https://deploy-preview-2427--oak-web-application.netlify.thenational.academy/pupils/lessons/atoms-elements-and-compounds-h3hasv/overview

thanks, have updated.

**Comment by messmike** [comment]
> > https://deploy-preview-2427--oak-web-application.netlify.thenational.academy/pupils/lessons/atoms-elements-and-compounds-h3hasv/overview
> 
> thanks, have updated.

The wording just needs to be updated to say:

> **Take me home**

E.g:
Screenshot 2024-05-20 at 10 55 49 am

**Review by RBrownsett — APPROVED** [review]
Tested via journey and canonical and each flow works as expected

**Pull request merged**
