### PR TITLE
[CUR-436] "thanks for downloading" `<SuccessMessage />` component

### PR DESCRIPTION
**Pull request by orangemug**
## Description

Music year: 1996

- Adds a new general purpose `<SuccessMessage/>` component for displaying success

## Issue(s)

Implements component part of `CUR-436`

## How to test

1. Go to storybook preview build
2. Checkout `/?path=/story/components-curriculumcomponents-successmessage--success-message`
3. You should see whats applied in the screenshots 

## Screenshots

Small
Screenshot 2024-04-23 at 15 06 58

Large

Screenshot 2024-04-23 at 15 07 25

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by HelenHarlow — APPROVED** [review]
Looks good to me!

**Review by rightsaidjames — COMMENTED** [review]
A few small design tweaks:

The body text might be missing style token(s) - the line height is wrong, and the font size is not explicit:
Screenshot 2024-04-23 at 15 42 44

The horizontal between the text and the image isn't large enough. I'm not sure if the image is tall enough, but I can't extract this info from Figma so it might be fine.
Screenshot 2024-04-23 at 15 46 34

**Comment by orangemug** [comment]
Thanks @rightsaidjames

I'm now using the correct body font as per the designs (although it looks a little weighty), it is `body1` so consistent with design (FYI @HelenHarlow) 

I've fixed the spacing issue in large screen, using the tokens `"space-between-m"` and `"all-spacing-16"` which appears in the right ballpark (_~120px_)

Is this close enough for y'all? It's a little difficult as the designs don't use the tokens everywhere, but we constrained within the codebase. Hopefully this will do the trick.

---

**Large** 

Screenshot 2024-04-24 at 10 31 02

**Medium**

Screenshot 2024-04-24 at 10 31 25

**Small**

Screenshot 2024-04-24 at 10 31 59

**Comment by BTitterington** [comment]
Looks good to me 👍. I know you've already merged, but would normally wait for an dev to review 🙂

**Pull request merged**
