### PR TITLE
LESQ-115 Feat/optionality title

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

add null variant title to units with optionality

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-1785--oak-web-application.netlify.thenational.academy
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Would this be possible to do? I think it better describes the layout of the page (currently everything is h3). Happy to put this in the styling ticket that comes later if you would prefer.

Screenshot 2023-08-10 at 14 05 11

**Comment by jack-skerrett-oak** [comment]
> Would this be possible to do? I think it better describes the layout of the page (currently everything is h3). Happy to put this in the styling ticket that comes later if you would prefer.
> 
> Screenshot 2023-08-10 at 14 05 11

We will do this on the styling pr

**Review by jack-skerrett-oak — APPROVED** [review]

**Review by k-huggs — COMMENTED** [review]
LGTM ✅

**Review by k-huggs — APPROVED** [review]

**Pull request merged**
