### PR TITLE
test: make every download restricted - LESQ-1065

### PR DESCRIPTION
**Pull request by JBR90**
## Description

Music year: {owa_music_year}

-  Previously only the lesson downloads from `account-security-68rkee` were geo-restricted behind a featureflag. This PR makes all download pages geo-restricted if you have `"isRegionAuthorised": false` and are using the featureflag.

## How to test

1. Go to https://deploy-preview-2774--oak-web-application.netlify.thenational.academy
Go to any downloads page (feature flag enabled) if you have `"isRegionAuthorised": false` in clerk you should see the
`Sorry, downloads for this lesson are not available in your country` page

## Screenshots

https://github.com/user-attachments/assets/2dfdaefa-faa0-4a6c-b51c-ef6dea6c1d75

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@JBR90 nice - just checking I noticed that I can still get to the download section for Specialist and therapies lessons. Are they included in this work?

**Comment by JBR90** [comment]
> @JBR90 nice - just checking I noticed that I can still get to the download section for Specialist and therapies lessons. Are they included in this work?

They should have been, just pushing up a change to fix that now.

**Review by RBrownsett — APPROVED** [review]
Approved: Tested with lessons from EYFS, KS1, KS2, KS3, KS4, Specialist and Therapies. Lessons are restricted when clicked download all, or individual lesson assets

**Review by njblore — APPROVED** [review]

**Pull request merged**
