### PR TITLE
CTC-96 and CTC-99 Automatically go to the next clip and page refresh fix on video change

### PR DESCRIPTION
**Pull request by weronika-szalas**
## Description

- Clip should automatically going to the next one when it ends (but not playing it straight away)

- There was a request that the last clip should switch state to “played” after it finishes playing - I haven't implemented it as if we set the last slip to "played" it won't be marked as an active item anymore and we will loose visual feedback of which item is currently selected. We should first add `active-played` status to the `OakMediaClipItem` in `oak-components`

Also fixed in this PR:
- [CTC-99](https://www.notion.so/oaknationalacademy/OWA-investigate-page-refresh-on-Media-page-15026cc4e1b1809291eec2cd433044c9) - the page reload on clip change
- a functionality Monika asked for before if possible - after choosing a video in the clip list the focus goes on the video (please test how screen reader announces it)

You should see the fixes from `oak-components` implemented
- box-shadow on cip list
- spacing in mobile view on Copy link button when there is no transcript
- focus on chevron from clip list when navigating with keyboard

## Issue(s)

Fixes [CTC-96](https://www.notion.so/oaknationalacademy/OWA-Media-page-autoplay-functionality-15026cc4e1b180b1b71fdaba4c1533e4)

## How to test

1. Go to https://deploy-preview-3052--oak-web-application.netlify.thenational.academy/teachers/programmes/design-technology-secondary-ks3-l/units/core-design-skills-a819/lessons/graphic-communication-cdhkat/media
2. Test the functionality

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by Monika-Koziol** [comment]
@weronika-szalas just looking at the requirements and checking if we understood them the same way. It was about automatically going to the next clip but not playing it straight away. Does that make sense?

**Comment by weronika-szalas** [comment]
> @weronika-szalas just looking at the requirements and checking if we understood them the same way. It was about automatically going to the next clip but not playing it straight away. Does that make sense?

Yes, I am sorry - I put the wrong title. My brain keeps calling it autoplay - I meant what you wrote above and that's what I've implemented too.

**Review by Monika-Koziol — APPROVED** [review]
@weronika-szalas thanks for this one. Do we have control of the time it takes to move to the next one? If we can make it quicker then great if not this one is fine as well.

**Review by RBrownsett — APPROVED** [review]
Tested - when video finishes the focus moves to the next video (but does not autoplay, which is the correct behaviour) Mobile view and tablet checked, no issues.
Current videos have not been affected by the change

**Review by k-huggs — APPROVED** [review]

**Pull request merged**
