### PR TITLE
[CUR-473] Added group role, aria-label and aria-pressed to domain/subject/tier buttons

### PR DESCRIPTION
**Pull request by orangemug**
## Description
- Added `role="group"` and `aria-label` to container divs for domain/subject/tier filters in curriculum visualiser
- Add `aria-pressed="true"` to currently active button in each filter group.

## Issue(s)

`CUR-473`

## How to test

1. Go to https://deploy-preview-2520--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary-edexcel/units
2. Test using voice over

### CODE REVIEW

**Comment by orangemug** [comment]
@rightsaidjames was this what you were thinking for `CUR-473`?

**Comment by orangemug** [comment]
Looks like sonar isn't happy https://github.com/oaknational/Oak-Web-Application/pull/2520#issuecomment-2179222138

Fair comment @rightsaidjames lets chat best approach

**Review by rightsaidjames — APPROVED** [review]
I'm happy with this result. It's not quite perfect, but it adds more semantics than before and makes it clearer what these buttons do and what their purpose is.

**Review by BTitterington — APPROVED** [review]

**Pull request merged**
