### PR TITLE
fix: wrap quiz hints in mathjax

### PR DESCRIPTION
**Pull request by kimon-satan**
## Bug Description

Quiz questions where  hints have a formula  eg. https://www.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/highest-common-factor-with-algebraic-terms/exit-quiz
are not being rendered with MathJax

## Fixes

- Wrapped the hint in MathJax

## How to test

1. Navigate to  https://deploy-preview-2667--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-year-7/units/expressions-and-equations/lessons/highest-common-factor-with-algebraic-terms/exit-quiz
2. Click ‘Need a hint?’
3. Observe that formulae is now rendered correctly

## Screenshots

How it used to look (delete if n/a):
image

How it should now look:
image

### ACs

- [x]  hints with formulae correctly rendered
- [x]  other hints unaffected

### CODE REVIEW

**Comment by kimon-satan** [comment]
> @kimon-satan looks good but for some reason question 4 in the quiz on the PR doesn't render all of the content correctly?
> 
> image

That looks like a content error to me. Only one $

**Comment by RBrownsett** [comment]
> > @kimon-satan looks good but for some reason question 4 in the quiz on the PR doesn't render all of the content correctly?
> > image
> 
> That looks like a content error to me. Only one $

So it is, just checked the CAT and its only one $

**Comment by kimon-satan** [comment]
> > > @kimon-satan looks good but for some reason question 4 in the quiz on the PR doesn't render all of the content correctly?
> > > image
> > 
> > 
> > That looks like a content error to me. Only one $
> 
> So it is, just checked the CAT and its only one $

Exactly it should be two for maths jax

**Review by RBrownsett — APPROVED** [review]
Approved - tested with math quiz hints and non math quiz hints - works as expected. Mobile and different browsers checked with no issues

**Review by benprotheroe — APPROVED** [review]

**Pull request merged**
