### PR TITLE
[PUPIL-793] Lesson review - update buttons

### PR DESCRIPTION
**Pull request by BTitterington**
## Description

Music year: 1958

This swaps the buttons on the lesson review page.

[Ticket here](https://www.notion.so/oaknationalacademy/Lesson-review-update-buttons-and-links-Beano-findings-73e928b7f7814467a3a3218feda915a8)

## How to test

1. Go to https://deploy-preview-2622--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-year-4/units/simple-compound-adverbial-and-relative-complex-sentences/lessons/three-sentence-types/review
2. There should be a link in the top left "Lesson overview" that takes you to the lesson overview
3. There should be a link in the bottom right "View all lessons" that takes you to all the lessons in that unit

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [x] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@BTitterington looks good, works as expected. In the Ac's it mentions data tracking is set up - is that something that is done in posthog?

**Comment by BTitterington** [comment]
@RBrownsett I was going to ask Aakesh. I'm pretty sure Simon has just fixed the tracking event for the review page, and I imagine you can setup something to see where they go after that event in posthog.

**Comment by RBrownsett** [comment]
> @RBrownsett I was going to ask Aakesh. I'm pretty sure Simon has just fixed the tracking event for the review page, and I imagine you can setup something to see where they go after that event in posthog.

Ah yep, you are right Simon did that yesterday

**Review by benprotheroe — APPROVED** [review]

**Review by messmike — APPROVED** [review]

**Pull request merged**
