### PR TITLE
Feat/lesq 1110/search results styling [LESQ-1110]

### PR DESCRIPTION
**Pull request by njblore**
## Description

Music year: 2004

- refactor search results item to be a clickable card rather than just the button/link on the card
- update styling for selected, expanded, hover and focus states of cards
- update spacing on search results page
- clean up component no longer in use

## How to test

1. Go to https://deploy-preview-2907--oak-web-application.netlify.thenational.academy/teachers/search?term=jekyll
2. You should see new hover, focus and expanded states matching designs: https://www.figma.com/design/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?node-id=8890-42311&node-type=canvas&m=dev 

## ACs

- [ ] matches designs
- [ ] events still fire (search result expanded and search result opened)
- [ ] links still work
- [ ] navigable by keyboard

### CODE REVIEW

**Comment by RBrownsett** [comment]
@njblore looking good. A couple of things relating to mobile view:

- When searching for a term that has tiers the results are returned with blue text - this only applies to iOS devices. Screenshots from Browser stack of iPhone and iPad 
OLD:
image
NEW:
image
image

- |The second issue (though this could be intended?) when I expand the tier section the search items remain highlighted as I click through other search items (see video for example)

https://github.com/user-attachments/assets/f6203a19-e751-4e18-8582-f079200d2b1c

**Review by k-huggs — COMMENTED** [review]
Code lgtm ✅

**Review by k-huggs — APPROVED** [review]

**Comment by njblore** [comment]
@RBrownsett the highlighting issue on mobile should be fixed now 🎉 
I can't reproduce the issue with the text colour (and text alignment?) :/ but I don't have any iOS device to test on, it's strange though as that text colour hasn't been changed, can't really think how that would be happening 🤔 are you able to inspect the element and check the hex value for the text?

**Comment by RBrownsett** [comment]
@njblore its an odd one - I've done some digging and it looks to be something do with how iOS handles buttons and it adds this code  `color: -apple-system-blue;`
image

There is some advice about how to get around it on this link https://stackoverflow.com/questions/74853859/how-to-avoid-safari-adding-apple-system-blue-to-my-button

The highlighting issues is now fixed though :-) 

I did notice that the search heading is missing on mobile view - 
OLD:
image

NEW:
image

**Review by RBrownsett — APPROVED** [review]
Approved - changes made, tested against mobile and desktop (iOS and Chrome, FireFox). Issues have been resolved.

**Pull request merged**
