### PR TITLE
[ENG-818] Additional logging through consent client

### PR DESCRIPTION
**Pull request by carlmw**
## Description

Music year: [1965](https://www.youtube.com/watch?v=MgJ9K7cPRKk)

- Bumps oak-consent-client@2.1.0
- Logs the first page a user landed on with the consent client as well as any UTM params

### CODE REVIEW

**Comment by simonrose121** [comment]
Just to confirm, are there no other changes required other than bumping the version?

**Comment by carlmw** [comment]
> Just to confirm, are there no other changes required other than bumping the version?

No other changes this is non-breaking. The API needs to be deployed to store the new data but the additional params will be ignored until then.

**Review by simonrose121 — APPROVED** [review]

**Review by mantagen — APPROVED** [review]
Love it

**Pull request merged**
