### PR TITLE
LESQ-707: Fix download and share buttons on lesson overview page

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 2000 - https://www.youtube.com/watch?v=MYxAiK6VnXw

- Download and share buttons on lesson overview navigate to specialist download and share pages

## Issue(s)

Fixes #LESQ-707

No assets for downloads however, share video below:

https://github.com/oaknational/Oak-Web-Application/assets/91190841/aee305d1-bec2-4873-a096-155444fa8387

### CODE REVIEW

**Review by njblore — APPROVED** [review]

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Sharing anything from legacy content 404s as it moves you to teachers/specialist/programmes rather than staying in teachers/programmes. Only when clicking on "share" from a specific resource, the share all at the top still works

https://deploy-preview-2323--oak-web-application.netlify.thenational.academy/teachers/programmes/music-primary-ks1-l/units/timbre-3b9d/lessons/exploring-different-ways-to-use-your-body-75k68t#slide-deck

**Comment by k-huggs** [comment]
> Sharing anything from legacy content 404s as it moves you to teachers/specialist/programmes rather than staying in teachers/programmes. Only when clicking on "share" from a specific resource, the share all at the top still works
> 
> https://deploy-preview-2323--oak-web-application.netlify.thenational.academy/teachers/programmes/music-primary-ks1-l/units/timbre-3b9d/lessons/exploring-different-ways-to-use-your-body-75k68t#slide-deck

This should be fixed ✅

**Review by jack-skerrett-oak — APPROVED** [review]
Sharing/downloading specific content now navigates a user to the correct share/download page

**Pull request merged**
