### PR TITLE
fix: correct subject fliters on search page LESQ-485

### PR DESCRIPTION
**Pull request by JBR90**
## Description

Music year: 2018

- [ ]  Remove Physics filter from old search api subject list
- [ ]  Fetch a list of unique subjects from both api’s

## Issue(s)

Fixes # LESQ-485

## How to test

1. Go to https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search
You should see a complete list of filter subject from new and old content.

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by njblore — APPROVED** [review]

**Comment by rightsaidjames** [comment]
I'm using the KS4 'tranverse waves' Combined Science/Physics unit as the basis for testing.

Searching for 'waves' brings up the right content alongside other legacy content that matches the keyword:
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&flag=enable_2023_search_api

Filtering by Physics (with or without the Units/Lessons and KS4 filter options selected) works as expected:
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&subjects=physics&flag=enable_2023_search_api
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&keyStages=ks4&subjects=physics
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&keyStages=ks4&subjects=physics&contentTypes=unit

As does filtering by Units/Lessons and/or KS4 without filtering by subject:
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&keyStages=ks4&contentTypes=unit&flag=enable_2023_search_api
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&contentTypes=lesson

**But** filtering by 'Combined Science' returns 0 results:
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&subjects=combined-science&flag=enable_2023_search_api
https://deploy-preview-2136--oak-web-application.netlify.thenational.academy/teachers/search?term=waves&keyStages=ks4&subjects=combined-science

Screenshot 2023-12-20 at 16 56 47
Screenshot 2023-12-20 at 16 56 54

At some point I was able to get this 'New' content to appear when filtering by Science, but I can't reproduce this now so it may have been feature flag weirdness.

**Comment by JBR90** [comment]
> teachers/search?term=waves&subjects=physics&flag=enable_2023_search_api

Thanks for the detailed feedback @rightsaidjames. I think i've got the bottom of this, seems like we need a small change the search API. I've written a ticket here - https://www.notion.so/oaknationalacademy/I-want-the-search-api-to-treat-subject-slugs-as-keywords-so-they-can-be-filtered-if-they-have-a-hyph-cd09b3ece6c14376937934a1dde22f23

I think we can get this in and then make the change in the search api -  it's hidden from users behind the flag anyway.

**Review by rightsaidjames — APPROVED** [review]
Sounds good @JBR90 - I'm happy with that approach, as long as m'learned colleague @jack-skerrett-oak agrees :)

**Review by jack-skerrett-oak — APPROVED** [review]

**Pull request merged**
