### PR TITLE
Feat/download card errors LESQ-406

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

- Adds new red colour to themes
- Updates formErrorMessages function
- Adds Icon to FieldError component and updates red
- Updates copy on messaging and test file
- Move position of error messages to above the section it is referring too (apart from list)

## AC:
- [x]  Add warning icon
- [x]  Move errors above the input fields
- [x]  Update error copy to be more descriptive (see Figma)
- [x]  Change the value of red colour from `failure: "#e51d4d"` to `red: "#DD0035"` (the new red is AAA for larger text and AA for smaller text)

## Issue(s)

Fixes #LESQ-406

## How to test

1. Go to https://deploy-preview-2054--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4-foundation-aqa/units/measuring-waves/lessons/transverse-waves/downloads
2. Clear local storage (or edit previously submitted details) if not done already to see the full downloads form
3. Deselect all, put in a fake email, don't enter a school name, don't accept terms and conditions to see all error messages
4. Click download to see bullet point list of error messages 

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-10-31 at 08 00 35
Screenshot 2023-10-31 at 08 00 13

How it should now look:
Screenshot 2023-10-31 at 08 10 16
Screenshot 2023-10-31 at 10 13 05

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [x] Design sign-off
- [x] Approved by product owner
- [x] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Moving the error above the input has caused the top input field in the newsletter form to have this padding error
Screenshot 2023-10-31 at 09 10 59

**Comment by JBR90** [comment]
When clicking through from a preselected resource it's not clear why the downloads button is disabled, i'm only getting a message when i select a resource manually. Is this the correct behaviour ?

**Review by jack-skerrett-oak — APPROVED** [review]

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
Not sure if this was part of this ticket TBH as it might be as it was working before. Ticking T&C doesn't automatically clear the error, which is a different behaviour from the resources and school picker. See the attached screenshot. 
Screenshot 2023-10-31 at 12 04 50

**Comment by k-huggs** [comment]
> Not sure if this was part of this ticket TBH as it might be as it was working before. Ticking T&C doesn't automatically clear the error, which is a different behaviour from the resources and school picker. See the attached screenshot. Screenshot 2023-10-31 at 12 04 50

Not a part of this ticket, but can add that in

**Review by JBR90 — APPROVED** [review]
LGTM

**Review by Monika-Koziol — APPROVED** [review]
Looking good @k-huggs

**Pull request merged**
