### PR TITLE
[CUR-935] Add multiple curriculum partners in docx

### PR DESCRIPTION
**Pull request by sonalisin**
## Description

Music year: 1988

- Added compatibility for multiple curriculum partners in the explainer section of the docx

## How to test

1. Go to https://deploy-preview-2885--oak-web-application.netlify.thenational.academy
2. Download any curriculum document with two curriculum partners
3. You should see them both in the docx
4. You should see no change in docx with a single curriculum partner 

## Screenshots

How it used to look (delete if n/a):

Screenshot 2024-10-14 at 17 39 13

Screenshot 2024-10-14 at 17 38 33

Screenshot 2024-10-14 at 17 39 58

How it should now look:

Screenshot 2024-10-14 at 17 35 26

Screenshot 2024-10-14 at 17 36 08

Screenshot 2024-10-14 at 17 41 27

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by orangemug** [comment]
@sonalisin I think we need a `isCycleTwoEnabled` check in this PR, else we'll be going live with the multiple partners prior to cycle 2 launch.

**Comment by rightsaidjames** [comment]
@orangemug I don't think it matters that this isn't behind the cycle 2 flag, as there are no cycle 1 lots with multiple partners.

**Review by HelenHarlow — APPROVED** [review]
I've had a look at the sample docs and it looks good to me! Thanks

**Review by rightsaidjames — APPROVED** [review]
Looks good. Tested with cycle 2 docs that do and don't have multiple partners, and also on the preview environment to check for no regressions with the cycle 1 version of the documents.

**Pull request merged**
