### PR TITLE
Feat/pupil 760/subcategories filter

### PR DESCRIPTION
**Pull request by kimon-satan**
## Description

When I select a unit listing with subject categories
I want to be able to filter the units by subject category
so that I can find the unit I'm looking for more easily

- List of changes

- Using new MV version and curriculum schema which expose denormalized subject categories
- Using new and modified OakComponents to render filter 
- Implement filter logic and tests

## How to test

https://deploy-preview-2604--oak-web-application.netlify.thenational.academy/pupils/programmes/english-primary-year-3/units

depending on whether production has been updated with subjectcategories for science units:
https://deploy-preview-2604--oak-web-application.netlify.thenational.academy/pupils/programmes/combined-science-secondary-year-10-foundation-aqa/units

examples without subjectcategories:
https://deploy-preview-2604--oak-web-application.netlify.thenational.academy/pupils/programmes/history-primary-year-2/units

## Screenshots

How it used to look (delete if n/a):
image

How it should now look:
image

## ACs

[x] Functional: Correct units are displayed for selected program - checked against the query below
[x] Functional: Check url - this should remain the same
[x] Functional: Check unit counts update
[x] Functional: Unit numbers keep the number from the ‘All’ filter
[x] Check Mobile view
[x] accessibility and screen reader

### CODE REVIEW

**Comment by kimon-satan** [comment]
ugh storybook is actually deployed fine but github is being stupid :/

**Comment by messmike** [comment]
- There are missing spaces between the heading and count for **Choose a unit(17)** & ### Choose a previously released unit(15) headings
- Accordion chevron icon update doesn't look to have been applied from the other ticket [https://github.com/oaknational/oak-components/pull/228#issuecomment-2228151207](https://github.com/oaknational/oak-components/pull/228#issuecomment-2228151207)
- Hide heading and empty state when no units to display as per [thread](https://oaknationalacademy.slack.com/archives/C0615EC080G/p1720513594621549):
Screenshot 2024-07-16 at 5 37 32 pm
- Some oddness happening to the tooltip when attempting to open when selecting another filter (I can raise a bug if needed): 
Screenshot 2024-07-16 at 5 42 25 pm

**Comment by kimon-satan** [comment]
> * There are missing spaces between the heading and count for **Choose a unit(17)** & **Choose a previously released unit(15)** headings
> * Accordion chevron icon update doesn't look to have been applied from the other ticket [Feat/pupil 833/pupil unit filter oak-components#228 (comment)](https://github.com/oaknational/oak-components/pull/228#issuecomment-2228151207)
> * Hide heading and empty state when no units to display as per [thread](https://oaknationalacademy.slack.com/archives/C0615EC080G/p1720513594621549):
>   Screenshot 2024-07-16 at 5 37 32 pm
> * Some oddness happening to the tooltip when attempting to open when selecting another filter (I can raise a bug if needed - although in this screengrab this won't be an issue if the section was hidden, so this may resolve itself):
>   Screenshot 2024-07-16 at 5 42 25 pm

hmmm. Except the hidden empty listings, these are all issues in oak-components. Not sure where and when these regressions have been introduced.

**Review by benprotheroe — APPROVED** [review]

**Review by BTitterington — APPROVED** [review]
Looks good. 👍

**Review by messmike — APPROVED** [review]

**Comment by RBrownsett** [comment]
@simonh-oak bit an odd one on unit numbering when selecting an optional unit in year 4 English and using the Reading, writing & oracy filter - the unit shows as 15 when the all filter is selected and checking the db the unit should be 15 - but shows as unit 5 when the oracy filter is selected

image

image

image

**Comment by kimon-satan** [comment]
> @kimon-satan bit of an odd one on unit numbering when selecting an optional unit in year 4 English and using the Reading, writing & oracy filter - the unit shows as 15 when the all filter is selected and checking the db the unit should be 15 - but shows as unit 5 when the oracy filter is selected
> 
> image
> 
> image
> 
> image

You mean Year 5 but I got it anyway ;) . Will fix now

**Comment by RBrownsett** [comment]
Approved - full testing details on the notion ticket

**Pull request merged**
