### PR TITLE
fix: update tab widths, tweak subject phase picker spacing

### PR DESCRIPTION
**Pull request by lioneljingles**
## Description

- Updated tab spacing and sizing to more closely match Figma designs
- Updated Subject Phase Picker spacing
- Fixed issue where certain subject icons would not appear

## How to test

1. Go to https://deploy-preview-1894--oak-web-application.netlify.thenational.academy/beta/teachers/curriculum/geography-primary/overview
2. You should see the tabs and subject phase picker match the [Figma design](https://www.figma.com/file/3cz9fb0ObFDLv1c212OtJv/High-fidelity-designs?node-id=1%3A367)
3. You should see the subject icon for Geography to the right of the curriculum title ("Primary Geography")
4. Click on the Subject Phase Picker subject control ("Subject / Geography")
5. You should see icons for all subjects
6. Open the Subject Phase Picker phase control ("Phase / Primary")
7. You should see side-by-side buttons for "Primary" and "Secondary"

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-09-11 at 16 19 01
Screenshot 2023-09-11 at 16 19 12
Screenshot 2023-09-11 at 16 19 19

How it should now look:
Screenshot 2023-09-11 at 16 18 02
Screenshot 2023-09-11 at 16 18 21
Screenshot 2023-09-11 at 16 18 30

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [x] Design sign-off
- [x] Approved by product owner

### CODE REVIEW

**Review by rightsaidjames — CHANGES_REQUESTED** [review]
The positioning/sizing of the subject icon on mobile in the header is not consistent with Figma when the subject name spans two lines. There is actually a bit of inconsistency in Figma, as in the Curric overview design it's top-aligned with the title, whereas on the unit sequence design it's vertically centred over the two lines. @HelenHarlow can you confirm which one is correct? My guess would be the latter, as this design is more recent and I think it looks nicer. 

Either way I don't think it should be how it currently looks! The size of the icon also looks too small to me.

Screenshot 2023-09-11 at 16 47 48
Screenshot 2023-09-11 at 16 42 29
-a196-4f59-82af-6478fb95ad86)

**Comment by lioneljingles** [comment]
> The positioning/sizing of the subject icon on mobile in the header is not consistent with Figma when the subject name spans two lines. There is actually a bit of inconsistency in Figma, as in the Curric overview design it's top-aligned with the title, whereas on the unit sequence design it's vertically centred over the two lines. @HelenHarlow can you confirm which one is correct? My guess would be the latter, as this design is more recent and I think it looks nicer.
> 
> Either way I don't think it should be how it currently looks! The size of the icon also looks too small to me.
> Screenshot 2023-09-11 at 16 47 48
> 
> Screenshot 2023-09-11 at 16 42 29
> 
> Screenshot 2023-09-11 at 16 44 14

Addressed in new release, please have a look!

**Review by HelenHarlow — APPROVED** [review]
Sorry missed that comment earlier! Yess correct, the icon was supposed to be centrally aligned when the text wraps over 2 lines, so this all looks good to me now 👍

**Review by rightsaidjames — APPROVED** [review]

**Comment by rightsaidjames** [comment]
Looks good, LGTM :+1

**Pull request merged**
