### PR TITLE
chore: update SEO on curric pages

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

- Excludes the lesson journey from the site map config file

## Issue(s)

Fixes #CUR-299

## How to test

1. Go to https://deploy-preview-2000--oak-web-application.netlify.thenational.academy

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by mantagen — APPROVED** [review]
lgtm

**Review by mantagen — CHANGES_REQUESTED** [review]
Shouldn't this be part of the "launch" PR

**Comment by kpopper** [comment]
> Shouldn't this be part of the "launch" PR

We agreed to keep it as a "soon after launch" thing.

**Review by njblore — APPROVED** [review]

**Review by jimCresswell — APPROVED** [review]

**Review by mantagen — APPROVED** [review]

**Pull request merged**
