### PR TITLE
fix: update subject phase picker options

### PR DESCRIPTION
**Pull request by lioneljingles**
## Description
- Integrate new subject phase options MV
- Show only options with published data
- Show all relevant exam boards for secondary science

## How to test

1. Go to https://deploy-preview-1932--oak-web-application.netlify.thenational.academy/teachers/curriculum
2. Click on `Subject`
3. You should see subjects with published data (note: Music not currently showing)
4. Click on `Science`
5. The Phase / Examboard section should open
6. Click `Secondary`
7. You should see multiple examboard choices

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-09-26 at 11 29 09
Screenshot 2023-09-26 at 11 28 55

How it should now look:
Screenshot 2023-09-26 at 11 28 13
Screenshot 2023-09-26 at 11 27 55

## Checklist

- [x] Added or updated tests where appropriate
- [x] Manually tested across browsers / devices
- [x] Considered impact on accessibility
- [x] Design sign-off
- [x] Approved by product owner

### CODE REVIEW

**Comment by rightsaidjames** [comment]
Shall we ignore `English > Secondary > Eduqas` for now? Looks good otherwise, I can see that different units are displayed for the Science exam boards.

**Comment by lioneljingles** [comment]
> Shall we ignore `English > Secondary > Eduqas` for now? Looks good otherwise, I can see that different units are displayed for the Science exam boards.

Is that a known issue? Unfortunately I've lost track...

**Comment by rightsaidjames** [comment]
> > Shall we ignore `English > Secondary > Eduqas` for now? Looks good otherwise, I can see that different units are displayed for the Science exam boards.
> 
> Is that a known issue? Unfortunately I've lost track...

Not really - it's been present for about a week, but I don't think we have an explanation for why it's occuring.

**Review by rightsaidjames — APPROVED** [review]
I think this should be merged because it gives us exam boards for Science. `English > Secondary > Eduqas` is still 404'ing, but this can be investigated separately.

**Review by k-huggs — APPROVED** [review]

**Pull request merged**
