### PR TITLE
[PUPIL-789] Pupil nav on 404 and 500

### PR DESCRIPTION
**Pull request by BTitterington**
## Description

Music year: 2011

Ticket [here](https://www.notion.so/404-500-Pupil-Navigation-2f96de8298774e7ab2799dc10062428e?pvs=23)

## How to test

Update - Just realised that all the preview builds currently have an issue with the 400 and 500 failing. Making this PR hard to test.

1. Go to https://deploy-preview-2517--oak-web-application.netlify.thenational.academy/pupils/does-not-exist
2. You should see a 404 with the pupil area selected

_

1. Go to homepage and check teachers is selected

_

1. Go to /pupils/years and check pupils is selected

NOTE: You may see teacher navigation initially selected, before it moves to pupil. This was unavoidable without adding server-side rendering to our 404 and 500 pages, which I don't believe was warranted as it may cause a larger issue in a large outage. 

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by BTitterington** [comment]
@RBrownsett - Just realised that all the preview builds currently have an issue with the 400 and 500 failing. Making this PR hard to test.

**Comment by RBrownsett** [comment]
> @RBrownsett - Just realised that all the preview builds currently have an issue with the 400 and 500 failing. Making this PR hard to test.

Ah yes - it shows the internal error page. I'll check there has been no adverse affects then test when it goes live

**Review by orangemug — APPROVED** [review]
Just tested locally, looks good to me!

**Comment by RBrownsett** [comment]
@BTitterington 404 works as expected - I did notice that when I tried to force a 500 error I got this page rather than the standard error page

image

Link I tried https://deploy-preview-2517--oak-web-application.netlify.thenational.academy/pupils/programmes/citizenship-secondary-year-11-l-12/units

**Comment by BTitterington** [comment]
> @BTitterington 404 works as expected - I did notice that when I tried to force a 500 error I got this page rather than the standard error page
> 
> image
> 
> Link I tried https://deploy-preview-2517--oak-web-application.netlify.thenational.academy/pupils/programmes/citizenship-secondary-year-11-l-12/units

Yes, spoke to Jim and the 500 is still not fixed. You can get to it by using this url https://deploy-preview-2517--oak-web-application.netlify.app/500 but that only tests it from a main site perspective. 

I think we're good to merge.

**Review by RBrownsett — APPROVED** [review]
Approved - tested with no issues

**Pull request merged**
