### PR TITLE
feat(package): latest oak compoents for d and d bug fix

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 1970

- List of changes
fix refresh bug for d and d quiz questions

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2556--oak-web-application.netlify.thenational.academy/pupils/programmes/combined-science-secondary-year-11-higher-edexcel/units/electromagnetic-waves/lessons/reflection-of-light/starter-quiz
2. Click on refresh
3. You should see the page should load without crashing

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@benprotheroe I still seem to get the 500 error when I refresh the starter quiz, and navigating directly also has the error https://deploy-preview-2556--oak-web-application.netlify.thenational.academy/pupils/programmes/combined-science-secondary-year-11-higher-edexcel/units/electromagnetic-waves/lessons/reflection-of-light/starter-quiz

image

**Comment by benprotheroe** [comment]
I merged oak-components pr, but don't know why it hasn't triggered a deploy

**Comment by benprotheroe** [comment]
> I merged oak-components pr, but don't know why it hasn't triggered a deploy

fixed!

**Review by RBrownsett — APPROVED** [review]
Approved - refresh and navigating to the page works and no 500 errors occur

**Pull request merged**
