### PR TITLE
Feat/pupil 1129/teacher expiring banner

### PR DESCRIPTION
**Pull request by kimon-satan**
### Job Story

**When** I navigate to a lesson or lesson listing which is due to be expired
**I want to see the new lesson takedown banner**
**So that users can plan appropriately**.

### Implementation details

The banner appears in response to the action “display_expiring_banner”

https://www.figma.com/design/dGO9erL0b0kpYxmv6Jku4f/Lessons-takedown-banners?node-id=2011-10285&m=dev

### Acceptance criteria

- [x]  banner matches design
- [x]  link goes to appropriate place
- [x]  teacher lesson page
- [x]  teacher lesson canonical page
- [x]  teacher lesson listing
- [x]  pa11y and percy

## How to test

Currently no expired lessons are available on production for testing

1. Go to https://deploy-preview-3058--oak-web-application.netlify.thenational.academy

VIsit legacy unitlistings, lesson listings and lessons for any of  

--   Legacy content to display expiry banner
--   ks1: ["english", "geography", "history", "science", "maths"],
--   ks2: [
--     "english",
--     "english-grammar",
--     "english-reading-for-pleasure",
--     "english-spelling",
--     "geography",
--     "history",
--     "science",
--     "maths",
--   ],
--   ks3: ["english", "history", "science", "maths"],
--   ks4: ["biology", "chemistry", "combined-science", "maths"]

Click on the view new resources buttons and check that the link goes to the unit listing or programmes page appropriately.

### CODE REVIEW

**Comment by messmike** [comment]
Example links:
legacy lesson listing - [https://deploy-preview-3058--oak-web-application.netlify.thenational.academy/teachers/programmes/history-secondary-ks3-l/units/how-dark-were-the-dark-ages-148d/lessons](https://deploy-preview-3058--oak-web-application.netlify.thenational.academy/teachers/programmes/history-secondary-ks3-l/units/how-dark-were-the-dark-ages-148d/lessons)
legacy lesson - [https://deploy-preview-3058--oak-web-application.netlify.thenational.academy/teachers/programmes/history-secondary-ks3-l/units/how-dark-were-the-dark-ages-148d/lessons/the-end-of-roman-britain-crv38r?sid-f8413f=sk069Dp9r9&sm=0&src=0](https://deploy-preview-3058--oak-web-application.netlify.thenational.academy/teachers/programmes/history-secondary-ks3-l/units/how-dark-were-the-dark-ages-148d/lessons/the-end-of-roman-britain-crv38r?sid-f8413f=sk069Dp9r9&sm=0&src=0)

**Comment by messmike** [comment]
@kimon-satan looks good. The sub-copy below the banner heading just needs updating to:

> Switch to our new teaching resources now - designed by teachers and leading subject experts, and tested in classrooms.

Screenshot 2024-12-10 at 3 10 38 pm

**Comment by kimon-satan** [comment]
> @kimon-satan looks good. The sub-copy below the banner heading just needs updating to:
> 
> > Switch to our new teaching resources now - designed by teachers and leading subject experts, and tested in classrooms.
> 
> Screenshot 2024-12-10 at 3 10 38 pm

gah sorry mike. I missed that

**Review by messmike — APPROVED** [review]

**Review by RBrownsett — APPROVED** [review]
Tested across the different key stages, banner is. displayed when expected and navigates to the correct page on action

**Pull request merged**
