### PR TITLE
Feat/restyle search bar LESQ-463

### PR DESCRIPTION
**Pull request by k-huggs**
## Re-style search bar component

Music year: 1956

- Changes styling of input box and button
- moves filter and changes color also 
- add mini-menu svg to cma
- removes title and text

## Acceptance Criteria:

- [x]  Remove instructional copy from the top of the page that says “*Search for topics and key words to explore thousands of lessons with adaptable teaching resources*”
- [x]  Remove the inputted search term (or the word “search” if no term is entered) at the top of the page above the search box (search box should always be the first thing on the page)
- [x]  remove yellow background behind search box on search page
- [x]  New styling of icon (rectangular background)

## Issue(s)

Fixes #LESQ-463

## How to test

1. Go to https://deploy-preview-2113--oak-web-application.netlify.thenational.academy
2. Search bar on home and search page should be input component
3. Search should continute to work as normal

## Screenshots

How it used to look:
Screenshot 2023-11-27 at 12 09 31:
Screenshot 2023-11-27 at 12 09 37

How it should now look:
Screenshot 2023-11-27 at 12 09 07
Screenshot 2023-11-27 at 12 09 19

## Checklist

- [x] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
Looking good. Just one small change can the word 'Search' be capitalised? At the moment it's all lower case.

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
- Capital s "Search" on homepage and search page
Screenshot 2023-11-27 at 13 33 58
- There is now no H1 on the page. We could make the tag on the search box a H1, but then would that also apply to the search box on the homepage? This also means that there are no H2s and instead we skip straight to h3, so we would need to change the results card to be H2 but I imagine that could happen on the search card ticket and we live with that small error for now. We will need to find a place for that h1 though!

**Review by JBR90 — APPROVED** [review]
Looks good, the only thing as an optional refactor would be to take the margin off the component and control that from the parent. But i know this is not how it was when you found it and perhaps we should have a discussion about when we should/shouldn't do this.

**Review by jack-skerrett-oak — APPROVED** [review]

**Review by Monika-Koziol — APPROVED** [review]
Looking good.

**Pull request merged**
