### PR TITLE
PUPIL-720 feat(subjects): fix padding on subject list

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 2010

fix padding on subject list

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2462--oak-web-application.netlify.thenational.academy
3. You should see correct padding

## Screenshots

Screenshot 2024-06-03 at 15 23 13

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by messmike** [comment]
Link here for review @RBrownsett: [https://deploy-preview-2462--oak-web-application.netlify.thenational.academy/pupils/years/year-4/subjects](https://deploy-preview-2462--oak-web-application.netlify.thenational.academy/pupils/years/year-4/subjects)

**Comment by messmike** [comment]
@benprotheroe, Thanks, I just noticed that the heading size for mobile needs updating to use `heading-6` if possible. E.g:

Screenshot 2024-06-03 at 3 36 29 pm

**Review by RBrownsett — APPROVED** [review]
Looks good to me

**Pull request merged**
