### PR TITLE
Dependagames 23rd October

### PR DESCRIPTION
**Pull request by orangemug**
## Description
[Dependalog](https://www.notion.so/oaknationalacademy/Dependa-games-7d461ecf33924ae699f5d4ce24b2dd0f?pvs=4#faed47d1e776414192aabbcffcec4d7b)

Nothing to QA:
 - `elliptic` — small changes to crypto nothing to QA
 - `dset` — fixes prototype pollution nothing to QA
 -  `graphql/codegen-cli` - used to generate graphql from queries, nothing to QA
 - `express`/`body-parser` — security fixes, this is used for build tooling, if the app works we should be good
 - `tsx`/`typescript` — https://github.com/oaknational/Oak-Web-Application/pull/2913
 - `react-cookie` — removed no longer used.
 - `babel/core` - compiler lib, no QA needed

QA requested:
 - `google/cloud-storage` - client lib for interacting with gcs, used for fetching video transcripts (new lessons only)
 - `mux/mux-player-react` - this is updated to version 3 so a major version update, changelog doesn't highlight any breaking changes but should QA videos in lessons and blogs
 - `clerk/nextjs` - lib used for interacting with clerk

### CODE REVIEW

**Review by rightsaidjames — APPROVED** [review]
Thanks for the notes on each dependency, really helpful for assessing risk and deciding what to test. I decided to put the parts of the site that rely on complex GraphQL queries through their paces just to make sure everything was definitely okay on that front.

Stuff tested:
- General clickthrough all areas of the site.
- Checked that the teacher and pupil browse journeys were functioning as normal and respected all the usual rules of programme/unit variance.
- Regression tested the curriculum visualiser.
- Checked the Mux player and transcript generation in the pupil journey, teacher journey, CMS pages and blog posts.
- Went through the onboarding journey with a fresh Google account (happy path only due to outstanding bug with the 'No' journey) and successfully downloaded.
- Also downloaded a curriculum document just in case!

LGTM!

**Review by rightsaidjames — COMMENTED** [review]
Actually one question @njblore  - I'm not seeing a dependency upgrade for `graphql/codegen-cli` in the `package.json` even though it's mentioned in the PR description - is this correct?

**Comment by rightsaidjames** [comment]
CC @orangemug (see question above)

**Comment by njblore** [comment]
@rightsaidjames so sorry, I didn't realise my last push failed which included graphql and mux updates - apologies! 🙇‍♀️

**Review by rightsaidjames — APPROVED** [review]
Retested as per my above comment, all good!

**Pull request merged**
