### PR TITLE
chore(deps): gleap update

### PR DESCRIPTION
**Pull request by johnrobeds**
## Description

Updates gleap package to latest 13.2.8

## Checklist

- [ ] Manually tested across browsers / devices
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by jack-skerrett-oak — COMMENTED** [review]
When I load up the deployment and accept statistic cookies, no gleap widget is displayed on the page

Screenshot 2024-01-17 at 08 59 16

**Comment by jimCresswell** [comment]
thanks @jack-skerrett-oak , I think it needed a rebuild to pick up the new config @mantagen added, I've kicked on off now

**Comment by jack-skerrett-oak** [comment]
> thanks @jack-skerrett-oak , I think it needed a rebuild to pick up the new config @mantagen added, I've kicked on off now

It seems to still be upset, complaining about CORS policy stuff
Screenshot 2024-01-17 at 12 40 00

**Comment by jimCresswell** [comment]
Tested by @mantagen

**Review by jimCresswell — APPROVED** [review]

**Pull request merged**
