### PR TITLE
wip: replacing homepage buttons with links

### PR DESCRIPTION
**Pull request by kimon-satan**
### Job Story

**When** I go to any landing page,
**I want to** make sure they are optimised for SEO
**So that we can** retain our ranking position and sitelinks.

## How to test

1. Go to https://deploy-preview-2759--oak-web-application.netlify.thenational.academy
2. You should see the that the 4 tab navigations are rendered as links

## Screenshots

How it used to look (delete if n/a):
image

How it should now look:
image

## Checklist

- [x] Buttons are links
- [x] Navigation works correctly
- [x] Styling preserved
- [x] mobile
- [x] keyboard navigation and screenreader

### CODE REVIEW

**Review by njblore — APPROVED** [review]
🎉

**Review by messmike — APPROVED** [review]

**Review by mantagen — COMMENTED** [review]
Hey! Looks like the 'active state' underline is a bit higher now, so there's a thin bit of white line underneath it?

**Comment by kimon-satan** [comment]
> Hey! Looks like the 'active state' underline is a bit higher now, so there's a thin bit of white line underneath it?

Hey matt. This is because I rebuilt the button using oak-components avoiding negative values for absolute positioning  which aren't tokens. The designers have reviewed and are happy with it and this ticket has been in circulation for quite a few days. So I ask whether we can park the discrepancy and create new backlog ticket if necessary 🙏

**Review by RBrownsett — APPROVED** [review]
Approved - screen reader works as expected with new links announced correctly. Mobile view and desktop is rendered with no issues.

**Review by mantagen — APPROVED** [review]

**Comment by mantagen** [comment]
@kimon-satan sure thing! Didn't mean it as a blocker just thought to mention it in case it hadn't been seen

**Pull request merged**
