### PR TITLE
Feat/ctc 38/update programme query

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 1990

### ACs

- [x]  new mv is used in query: published_mv_synthetic_unitvariant_lessons_by_keystage_13_0_0
- [x]  schema is updated
- [x]  overrides and exceptions are implemented
- [x]  navigation is uneffected by changes

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-3002--oak-web-application.netlify.thenational.academy/teachers/key-stages/ks4/subjects/maths/programmes
2. Click on other programme pages
3. You should see no chnges to 

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@benprotheroe @kimon-satan just checking - the new science units that display now in the KS4 teacher area 'Energy of moving particles' and 'Maintaining biodiversity' and human impacts go to a 404 page - which PR will ensure those units go to the lesson listing page?

**Comment by RBrownsett** [comment]
@benprotheroe @kimon-satan ignore my last comment, its this PR https://github.com/oaknational/Oak-Web-Application/pull/3001#issuecomment-2485983091 that fixes the lesson listing page

**Comment by kimon-satan** [comment]
> @benprotheroe @kimon-satan just checking - the new science units that display now in the KS4 teacher area 'Energy of moving particles' and 'Maintaining biodiversity' and human impacts go to a 404 page - which PR will ensure those units go to the lesson listing page?

yes thats expected. They won't work until the lessonListingQuery ticket is completed

**Review by RBrownsett — APPROVED** [review]
Approved - tested program pages and compared against live, no regression issues

**Pull request closed without merging**
