### PR TITLE
Feat/pupil 798/prominent quiz stem instructions

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 1979

- List of changes
Add jauntyAngleLabel component into puoil quizzes

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2637--oak-web-application.netlify.thenational.academy/pupils/programmes/english-secondary-year-11-aqa/units/modern-text-first-deep-dive-169/lessons/introductions-and-conclusions-about-education-in-animal-farm/starter-quiz
2. Click on start quiz
3. You should see jaunty angle label in use
4. Click on exit quick, navigate to question 4 and see the use of jaunty angle label for multi angle question type

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by messmike** [comment]
Looks good, thanks Ben. Is it possible to apply the jaunty label to the jauntyAngleLabel component to short answer questions? Eg: 
Screenshot 2024-07-24 at 2 20 11 pm

(match and order questions are n/a)

**Review by messmike — APPROVED** [review]

**Comment by RBrownsett** [comment]
@benprotheroe for consistency is it possible to display 'select two answers' rather than 'select 2 answers'?  
Screenshot 2024-07-24 at 16 44 21

Screenshot 2024-07-24 at 16 45 11

**Comment by benprotheroe** [comment]
> @benprotheroe for consistency is it possible to display 'select two answers' rather than 'select 2 answers'? Screenshot 2024-07-24 at 16 44 21
> 
> Screenshot 2024-07-24 at 16 45 11

Im not opposed to it; maybe we could use this dependancy https://www.npmjs.com/package/number-to-words @kimon-satan

**Review by RBrownsett — APPROVED** [review]
Approved - decision made by the squad to leave the numbering as it is. Checked free text answer, MCQ quiz questions with more than 1 answer required. No regression issues on other quiz types. 

Tested in mobile, tablet and desktop

**Review by kimon-satan — APPROVED** [review]

**Pull request merged**
