### PR TITLE
PUPIL-351: Pupil lesson copy changes

### PR DESCRIPTION
**Pull request by carlmw**
Music year: [2006](https://www.youtube.com/watch?v=x1peC9_QOiE)

## Description

A bunch of copy changes and tweaks to match the [latest designs](https://www.figma.com/file/G7z5ufo2T0CHk14CkadeuB/Pupils-high-fidelity-designs?type=design&node-id=2980-64457&mode=design)

# Caveats
1. The "Lesson review" button label will appear at the end of the exit quiz even if the lesson is incomplete (I.e. the lesson has been completed out of order). I feel like this ok, but I can spend a little more time covering this case if it would be confusing. In the case that the lesson is completed out of order this label should be applied to any section that happens to be the last one completed.
2. I missed changing the "Watch video"  -> "Lesson video" on the lesson review page. This will trickle through in the next publish of the components library with this PR https://github.com/oaknational/oak-components/pull/107

## How to test

1. Go to https://deploy-preview-2255--oak-web-application.netlify.thenational.academy/pupils/programmes/maths-secondary-ks3/units/graphical-representations-of-data/lessons/constructing-bar-charts-by-utilising-technology
3. Take the lesson
4. The copy should match the latest designs

## Screenshots
Screenshot 2024-02-15 at 13 15 22
Screenshot 2024-02-15 at 13 15 04
Screenshot 2024-02-15 at 13 14 58
Screenshot 2024-02-15 at 13 14 47
Screenshot 2024-02-15 at 13 14 31
Screenshot 2024-02-15 at 13 14 07
Screenshot 2024-02-15 at 14 03 38

### CODE REVIEW

**Comment by messmike** [comment]
All good from me @carlmw, and you already covered the "Watch video" -> "Lesson video" on the lesson review page in the caveats above which was the only thing from me.

**Review by messmike — APPROVED** [review]

**Comment by rightsaidjames** [comment]
Screenshots look good, but I'll have a proper run through on Monday to make sure it all holds together and makes sense as a whole.

I agree with your reasoning for not making the exit quiz final button text not context aware at this point, one for the backlog of quick wins post-launch I think.

**Review by rightsaidjames — APPROVED** [review]
Had a quick look and all looks to be as per the spec. There's a few other edge cases to consider (e.g. if you watch the video first the CTA button will be 'Let's get ready', but if you do the starter quiz first the CTA button will be 'Continue lesson'. Therefore I think we should have a follow up ticket that tightens up this logic so that the most sensible button text will be used even if the lesson is done in the wrong order.

image
image

**Pull request merged**
