### PR TITLE
LESQ-1043: Fixes across the sign up/onboarding journey

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 2014

- Adds DOM manipulation code to the layout component
- fixes width on enter school manually button
- Updates clerk to render sign up page and corresponding test file

## Issue(s)

Fixes #LESQ-1043

Acceptance Criteria:
- [ ] The mobile spacing of the school picker seems weird, it should probably just stay on one line
- [ ] The top of the form is cropped off when at mobile widths
- [ ] The “Other” input field overlaps with the radio button, and the error state is also hidden behind the label
- [ ] We want users to be taken to the sign up page rather than the sign in page by default (AI squad currently do sign in, might want to talk to them to make this consistent)
- [ ]  The terms and conditions loads in before the form/when the form isn’t there and it sometimes looks a little odd, see video. This gets worse the slower your connection speed is

Note:

The below acceptance criteria have been omitted
- [ ] You can’t use the browser’s back button to navigate out of the sign up journey back to the lesson page (somewhat intermittent… I think?). You can see in the recording one back button press keeps me on the sign up form. Another button press takes me to the unit listing page
- [ ] Focus states! There is something funky happening with the focus states throughout the sign up journey, as well as other places in OWA. Seems to be weird across both buttons and links

## How to test

1. Go to https://deploy-preview-2746--oak-web-application.netlify.thenational.academy
2. Click on \_\_\_\_\_\_
3. You should see \_\_\_\_\_\_

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
Just adding those here as they got missed, most of it is copy. 

- [x] newsletter copy shoud say: `Sign up for our latest resources and updates by email. Unsubscribe at any time. `
- [x] can we add additional top and bottom padding of 24px to the main CTA. 
- [x] role choices the one before last should say: `Working at an educational nonprofit`
- [x] on school picker dropdown it should say: `Select your school `(enter school's details stays on the manual entry)

Looking good otherwise.

**Comment by RBrownsett** [comment]
@k-huggs I'll be picking this one up from a QA point of view- do you have the testing steps so I can have a look at it?

**Comment by njblore** [comment]
> can we add additional top and bottom padding of 24px to the main CTA.

@Monika-Koziol do you mean on the sign up page or the onboarding page?

**Comment by Monika-Koziol** [comment]
@njblore I meant the onboarding page just to give it a bit more breathing space.

**Comment by RBrownsett** [comment]
@njblore looking good - just checking the font weight for the 'Enter manually' text has gone from 700 to 300 as part of this change - is that intentional? I noticed its still 700 for the 'Select from dropdown' text. 

image

**Comment by njblore** [comment]
@RBrownsett pretty sure that was unintentional! should be fixed on the next build

**Review by RBrownsett — APPROVED** [review]
Approved - tested scenarios listed, and tested rendering in mobile view, no issues.

**Review by Monika-Koziol — APPROVED** [review]

**Pull request merged**
