### PR TITLE
chore(deps): minor updates

### PR DESCRIPTION
**Pull request by johnrobeds**
## Description

[@axe-core/react](https://github.com/dequelabs/axe-core-npm) updated to ^4.8.1
 [@babel/core](https://github.com/babel/babel) updated to ^7.23.3
 [@google-cloud/storage](https://github.com/googleapis/nodejs-storage) updated to ^7.6.0
 [@hookform/resolvers](https://github.com/react-hook-form/resolvers) updated to ^3.3.2
 [@mux/mux-node](https://github.com/muxinc/mux-node-sdk) updated to ^7.3.3
 [@react-aria/aria-modal-polyfill](https://github.com/adobe/react-spectrum) updated to ^3.7.7
 [@sanity/client](https://github.com/sanity-io/client) updated to ^6.7.1
 [@slack/bolt](https://github.com/slackapi/bolt-js) updated to ^3.14.0
 [@storybook/addon-a11y](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-actions](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-docs](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-essentials](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-interactions](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-links](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-mdx-gfm](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/addon-storysource](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/cli](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/nextjs](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/react](https://github.com/storybookjs/storybook) updated to ^7.5.3
 [@storybook/testing-library](https://github.com/storybookjs/testing-library) updated to ^0.2.2
 [@testing-library/react](https://github.com/testing-library/react-testing-library) updated to ^14.1.0
 [@testing-library/user-event](https://github.com/testing-library/user-event) updated to ^14.5.1
 [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^29.5.8
 [@types/js-cookie](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^3.0.6
 [@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^18.2.37
 [@types/react-transition-group](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^4.4.9
 [@types/styled-components](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^5.1.30
 [@types/uuid](https://github.com/DefinitelyTyped/DefinitelyTyped) updated to ^9.0.7
 [@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint) updated to ^6.10.0
 [@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint) updated to ^6.10.0
 [@wdio/browserstack-service](https://github.com/webdriverio/webdriverio) updated to ^8.22.1
 [@wdio/cli](https://github.com/webdriverio/webdriverio) updated to ^8.22.1
 [@wdio/local-runner](https://github.com/webdriverio/webdriverio) updated to ^8.22.1
 [@wdio/mocha-framework](https://github.com/webdriverio/webdriverio) updated to ^8.22.0
 [@wdio/spec-reporter](https://github.com/webdriverio/webdriverio) updated to ^8.21.0
 [better-react-mathjax](https://github.com/fast-reflexes/better-react-mathjax) updated to ^2.0.3
 [chromedriver](https://github.com/giggio/node-chromedriver) updated to ^119.0.1
 [dotenv](https://github.com/motdotla/dotenv) updated to ^16.3.1
 [googleapis](https://github.com/googleapis/google-api-nodejs-client) updated to ^128.0.0
 [graphql](https://github.com/graphql/graphql-js) updated to ^16.8.1
 [jest](https://github.com/jestjs/jest) updated to ^29.7.0
 [jest-environment-jsdom](https://github.com/jestjs/jest) updated to ^29.7.0
 [postcss-scss](https://github.com/postcss/postcss-scss) updated to ^4.0.9
 [posthog-js](https://github.com/PostHog/posthog-js) updated to ^1.88.3
 [posthog-node](https://github.com/PostHog/posthog-node) updated to ^3.1.3
 [properties-file](https://github.com/Avansai/properties-file) updated to ^3.3.7
 [start-server-and-test](https://github.com/bahmutov/start-server-and-test) updated to ^2.0.2
 [swr](https://github.com/vercel/swr) updated to ^2.2.4
 [typescript-plugin-css-modules](https://github.com/mrmckeb/typescript-plugin-css-modules) updated to ^5.0.2
 [wdio-wait-for](https://github.com/webdriverio/wdio-wait-for) updated to ^3.0.8
 [webpack](https://github.com/webpack/webpack) updated to ^5.89.0
 [yargs](https://github.com/yargs/yargs) updated to ^17.7.2
 [zod](https://github.com/colinhacks/zod) updated to ^3.22.4

## Checklist

- [x] Manually tested across browsers / devices
- [X] Approved by product owner

### CODE REVIEW

**Review by jimCresswell — APPROVED** [review]
The code changes and checks seem good to me! Given the number of changes I do think it would be wise to wait for a manual QA review

**Comment by johnrobeds** [comment]
@rightsaidjames @jack-skerrett-oak is one of you able to give this a manual QA please?

**Review by rightsaidjames — APPROVED** [review]
I've had a click through the site and everything seems hunky-dory!

**Pull request merged**
