### PR TITLE
Feat/lesq 348/lesson overview info

### PR DESCRIPTION
**Pull request by kimon-satan**
## Description

- [x]  Year - Tier - Exam board
- [x]  Pupil Lesson outcome added to header
- [x]  Add new tag for new content in header
- [x]  Change download button icon
- [x]  Remove the extra lines between the last component and footer
- [x]  Make sure the the last resource item has a 56px bottom padding so there is a gap between that and the footer
- [x]  Make the divider lines between the components pink #DEB7D5
- [x]  Correct typo on copyright box. Title should be `Licence` not License
- [x]  Remove the Additional materials iframe and implement the workaround design ([[bottom of this frame](https://www.figma.com/file/3i0y2PHT6pECaGgvLhoN8z/Lesson-page-July-2023?type=design&node-id=2393-74473&mode=design&t=6RPaPfV6RNLVrVJd-4)](https://www.figma.com/file/3i0y2PHT6pECaGgvLhoN8z/Lesson-page-July-2023?type=design&node-id=2393-74473&mode=design&t=6RPaPfV6RNLVrVJd-4))

## How to test

1. Go to https://deploy-preview-1972--oak-web-application.netlify.thenational.academy/teachers/programmes/history-secondary-ks3/units/the-norman-conquest-how-do-we-know-about-the-impact-of-the-conquest-on-england/lessons/norman-changes-to-english-land-tenure

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by JBR90 — APPROVED** [review]
LGTM

**Review by Monika-Koziol — APPROVED** [review]
Looking good.

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
- Looks like we are fetching the wrong field as tiers aren't capitalised https://deploy-preview-1972--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-edexcel/units/macbeth-and-masculinity-the-struggle-for-power/lessons/duncan-as-a-father-figure
- The approach for doing the Year - Exam board - Tier thing is different here than it is on the lesson listing page, would it make sense to make them consistent? (Yours is inside one span)
- Having the "bullet" read out by the screen reader isn't necessary (I thought I had commented about that on the PR for lesson listing page but maybe it got missed)
- There is a visual cue to say you will be moved to another page for downloading a, but not an accessible one... maybe that is a ticket for another day as all the links on the page will need a solution
- The ticket says 56px of padding but it seems to be 80px
Screenshot 2023-10-04 at 15 40 00
- I feel like the sentence explaining the absence of additional materials is missing a "the". "We're sorry, but THE preview is not currently available".. might just be me overthinking though!

**Comment by kimon-satan** [comment]
> * Looks like we are fetching the wrong field as tiers aren't capitalised https://deploy-preview-1972--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-edexcel/units/macbeth-and-masculinity-the-struggle-for-power/lessons/duncan-as-a-father-figure
- This is an MV issue - agreed with Verity to make it a backlog ticket
> * The approach for doing the Year - Exam board - Tier thing is different here than it is on the lesson listing page, would it make sense to make them consistent? (Yours is inside one span) 
- Ugh didn't notice the existing component. Will change it
> * Having the "bullet" read out by the screen reader isn't necessary (I thought I had commented about that on the PR for lesson listing page but maybe it got missed)
- what bullet ?
> * There is a visual cue to say you will be moved to another page for downloading a, but not an accessible one... maybe that is a ticket for another day as all the links on the page will need a solution
- it's a button as link so the screen reader knows it goes to another page ?
> * The ticket says 56px of padding but it seems to be 80px
- was inconsistent with the Figma. Checked with monika and she tolkd me 80px
>   Screenshot 2023-10-04 at 15 40 00
> * I feel like the sentence explaining the absence of additional materials is missing a "the". "We're sorry, but THE preview is not currently available".. might just be me overthinking though!
- Just following instructions here

**Review by jack-skerrett-oak — APPROVED** [review]

**Comment by Monika-Koziol** [comment]
@jack-skerrett-oak and @kimon-satan  I've approved 80px looked beet on the site. And if we need "the" then we should add it.

**Pull request merged**
