### PR TITLE
chore: update exam board copy CUR-297

### PR DESCRIPTION
**Pull request by JBR90**
## Description

- [ ]  Text “All sequences are identical at KS3” is shown in subject phase picker where there are exam-board choices available
- [ ]  The text is not shown where it is not

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-1983--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-primary/overview
2. Click on _______
3. You should see _______
image

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]

**Comment by rightsaidjames** [comment]
Looks good to me! (note that Maths does not have exam boards, so does not display this notice)
Screenshot 2023-10-09 at 08 50 21
Screenshot 2023-10-09 at 08 52 29
Screenshot 2023-10-09 at 08 52 57
Screenshot 2023-10-09 at 08 53 10
Screenshot 2023-10-09 at 08 53 42

**Review by rightsaidjames — APPROVED** [review]

**Review by HelenHarlow — COMMENTED** [review]
Hey Joe! So sorry to be a pain (I hadn't seen this ticket), but we decided on the final iteration of this design yesterday which looks like this:
Screenshot 2023-10-10 at 09 20 57

We would therefore need to adjust the exam board title and remove the body copy. Hope that's ok!

**Review by HelenHarlow — APPROVED** [review]
Looks good, thanks Joe!

**Review by rightsaidjames — APPROVED** [review]

**Pull request merged**
