### PR TITLE
feat(printable): create style printable results page

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 2006

- List of changes
PUPIL-967 - printable results page 

now when a pupil finishes a lesson and presses get printable results they're results are stored locally and they can see the printable results page

- owa points to pupil-api prod
- video completion percentage is accurate

### Acceptance criteria

- [x]  pupils/results/print/[lessonSlug]/[attemptId]
- [x]  fetches results from localStorage
- [x]  loading state
- [x]  tests

PUPIL-1033 - styling
I have piggy backed the styling ticket for results page here; so both share page and printable page have mikes styling.

figma
https://www.figma.com/design/G7z5ufo2T0CHk14CkadeuB/Pupil-Lesson?node-id=10015-27969&node-type=canvas&t=OwKu20WMfailZlrk-0
## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2810--oak-web-application.netlify.thenational.academy
2. Click on a lesson; finish a lesson; on review page you should see two buttons; pritable and share; printable should take you to the styled printable page and share after loading will give you a url of the styled share page

note. you need to change the url from "thenational.academy" to "https://deploy-preview-2810--oak-web-application.netlify.thenational.academy"

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by RBrownsett** [comment]
@benprotheroe just out of interest how does it know how much of the video I completed? In this instance I did not play the video but it states I completed 80% ? 
image

**Comment by messmike** [comment]
Thanks @benprotheroe, just a few comments on the styling of the printable results page:

- In the banner at the top of the page, will we be able to provide a link to the review page by linking the words "Lesson review page"?
- There looks like a couple of spaces after "Worksheet downloaded - No". Is it possible to align this to the left and remove the additional space?
- At the very bottom of the results, can we add a little additional spacing, and also the legal text/copyright? E.g: 
Screenshot 2024-09-23 at 4 32 56 pm

- Not a big one really, but for "Question hint used - false" could we say either "Yes" or "No" instead of "true" or "false"?
- To your point the other day (and something @RBrownsett pointed out), when going to print the results the size of text and spacing in that view takes up a lot of pages. One for another ticket, maybe to look at stripping out styling and having one smaller font size in a plain format that is printer-friendly? 
[Oak National Academy.pdf](https://github.com/user-attachments/files/17100256/Oak.National.Academy.pdf)

- side note - I didn't see a loading state for the page, but guessing that is because I have a fast connection

**Comment by RBrownsett** [comment]
@benprotheroe looking good - a few comments:

Functional:
When I access a hint this is not recored in the printable results, displayed as False when should be True

Print Results:
The quiz hint text covers the answers in some scenarios (when the answer is long):
image


For Short answer questions would it be better to just show the default answer rather than all of the potential options? It takes up a lot of space e.g

image


Share Results:
Issues in mobile view 
image

As @messmike mentioned we have a lot of white space due to the font. No sure if it would be better having a Share component that has styling then a second component for the Print results page - just a thought

**Comment by messmike** [comment]
@benprotheroe This might be for a separate ticket, but I've mocked up a more simplified version of the print results page that would take up fewer pages when printing: [https://www.figma.com/design/G7z5ufo2T0CHk14CkadeuB/Pupil-Lesson?node-id=10561-34141&m=dev](https://www.figma.com/design/G7z5ufo2T0CHk14CkadeuB/Pupil-Lesson?node-id=10561-34141&m=dev)

**Review by kimon-satan — APPROVED** [review]

**Pull request merged**
