### PR TITLE
feat: skip button for lesson overview - LESQ-761

### PR DESCRIPTION
**Pull request by JBR90**
## Description

Music year: 1966

- Adds skip button to lesson overview item container (video / slide / worksheet)
- Button is only visible when focused
- Button takes you to the next item (resource) on the page

## How to test

1. Go to https://deploy-preview-2558--oak-web-application.netlify.thenational.academy
Tab through lesson overview page, you should see skip button appearing when focused, pressing button should skip content and take you to the the next item.

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by rightsaidjames — APPROVED** [review]
This works, but it seems a little over-engineered - is there any reason why these couldn't be plain anchor links instead of buttons? I notice that the same pattern is used for the in-page sidebar nav, but the skip link on the search results page is a literal link element (same goes for the 'Skip to units' button in the Curriculum visualiser).

I have agreed with @jack-skerrett-oak that this should be approved, but he will create a backlog ticket to investigate converting these skip buttons into skip links.

Tested with a keyboard and VoiceOver (macOS Chrome), works as expected.

Boomer screenshot showing the buttons in the Rotor:
IMG_1301

**Comment by JBR90** [comment]
> This works, but it seems a little over-engineered - is there any reason why these couldn't be plain anchor links instead of buttons? I notice that the same pattern is used for the in-page sidebar nav, but the skip link on the search results page is a literal link element (same goes for the 'Skip to units' button in the Curriculum visualiser).
> 
> I have agreed with @jack-skerrett-oak that this should be approved, but he will create a backlog ticket to investigate converting these skip buttons into skip links.
> 
> Tested with a keyboard and VoiceOver (macOS Chrome), works as expected.
> 
> Boomer screenshot showing the buttons in the Rotor: IMG_1301



> This works, but it seems a little over-engineered - is there any reason why these couldn't be plain anchor links instead of buttons? I notice that the same pattern is used for the in-page sidebar nav, but the skip link on the search results page is a literal link element (same goes for the 'Skip to units' button in the Curriculum visualiser).
> 
> I have agreed with @jack-skerrett-oak that this should be approved, but he will create a backlog ticket to investigate converting these skip buttons into skip links.
> 
> Tested with a keyboard and VoiceOver (macOS Chrome), works as expected.
> 

Thanks James, was purely based on the designs which used the secondary button. I didnt realise this could be changed to an 'a'. Just pushing up a change now.

**Review by njblore — APPROVED** [review]

**Review by rightsaidjames — APPROVED** [review]
Retested with skip links instead of buttons - working the same as before (except that they are links and not buttons, which is more in line with users' expectations). The skip links appear in the `Links` menu of the VoiceOver Rotor instead of `Form Controls`.

**Pull request merged**
