### PR TITLE
feat/exam-board-search-filter LESQ-479

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 1968

- Adds exam board search filters
- Points search page at Database-Tools rather than Data-Tools
- Updates SDK
- Updates test files, types and schemas
- Updates the Elastic Query and Test file

## Issue(s)

Fixes #LESQ-479

## How to test

1. Go to https://deploy-preview-2135--oak-web-application.netlify.thenational.academy
2. Click on search page
3. You should see exam board filters
4. Will filter new content by exam board

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-12-19 at 09 07 22

How it should now look:
Screenshot 2023-12-19 at 09 08 03

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by JBR90 — APPROVED** [review]
LGTM

**Review by JBR90 — APPROVED** [review]
LGTM

**Comment by njblore** [comment]
I'm not sure if it's something with the feature flag but the filters aren't working for me

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
A real deal breaker for me here Kyle.... could "Exam Board" be changed to "Exam board" please :D 

I had a bit of trouble verifying the behaviour because the feature flag was acting up, but I think it is behaving as expected. I will do another test on the branch to remove the flag!

**Review by jack-skerrett-oak — APPROVED** [review]

**Pull request merged**
