### PR TITLE
Added styling to curriculum explainers in docx

### PR DESCRIPTION
**Pull request by orangemug**
## Description
Added styling to curriculum explainers in docx, also

 - Disabled list of thread for cycle 2
 - Removed subject principals for cycle 2

## Issue(s)

Fixes `CUR-894`

## How to test
Cycle 1

1. Go to https://deploy-preview-2816--oak-web-application.netlify.thenational.academy
2. Check for regressions in curriculum download (docx)

Cycle 2: enable cycle 2 locally 

1. Go to https://deploy-preview-2816--oak-web-application.netlify.thenational.academy
2. Check explainers curriculum download (docx) display correctly

### CODE REVIEW

**Comment by rightsaidjames** [comment]
@HelenHarlow I've generated a few documents so you can check the styling of the explainers, do you want to take a look?

[Maths - Secondary - Foundation - 25-09-2024.docx](https://github.com/user-attachments/files/17131666/Maths.-.Secondary.-.Foundation.-.25-09-2024.docx)
[Geography - Secondary - AQA - 25-09-2024.docx](https://github.com/user-attachments/files/17131667/Geography.-.Secondary.-.AQA.-.25-09-2024.docx)
[English - Secondary - AQA - 25-09-2024.docx](https://github.com/user-attachments/files/17131669/English.-.Secondary.-.AQA.-.25-09-2024.docx)

**Review by rightsaidjames — APPROVED** [review]
Approved from a regression testing perspective, and also a functional perspective for the new explainers, but I defer judgement to @HelenHarlow on the design accuracy!

**Review by HelenHarlow — APPROVED** [review]
Looks good! One really small change, in the test docs there are a couple of places where there isn't enough space between some of the sub sections e.g. between the reading lists in English, and between the lists for subject-specific needs in geog. If we can add some extra spacing to separate those sections further that would be ideal!
Screenshot 2024-09-25 at 17 13 56

Screenshot 2024-09-25 at 17 13 37

**Comment by orangemug** [comment]
Interesting, I'm not seeing those spacing issues, are you @rightsaidjames ?

**Review by assadk88 — APPROVED** [review]

**Pull request merged**
