### PR TITLE
LESQ-246 fix(listing card): fix padding

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description
padding

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-1992--oak-web-application.netlify.thenational.academy/teachers/programmes/english-secondary-ks4-edexcel/units
2. Click on _______
3. You should see _______

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
The changes have only been made to the unit listing card, the ticket asks for them on the lesson listing as well. I don't know if the changes have been made to the optionality one as well, we don't have that on the site anymore.

**Comment by kimon-satan** [comment]
> The changes have only been made to the unit listing card, the ticket asks for them on the lesson listing as well. I don't know if the changes have been made to the optionality one as well, we don't have that on the site anymore.

I can see changes to lessonListingItem now so I think Ben has done this. Can you confirm this is correct ?

This is optionality (looks wrong on the left to me)
image

Ben mock it up in story book and fix

**Review by kimon-satan — APPROVED** [review]

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
- We still need 12px padding all the way around the title on the mobile lesson listing component https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=927-7802&mode=dev
Screenshot 2023-10-09 at 16 35 31
- May as well fix the desktop lesson listing component as well. That one has 24px padding all the way around the content https://www.figma.com/file/YcWQMMhHPVVmc47cHHEEAl/Oak-Design-Kit?type=design&node-id=1898-9846&mode=dev

**Review by jack-skerrett-oak — APPROVED** [review]
Get it gone

**Pull request merged**
