### PR TITLE
Feat/lesq 801/homepage updates [LESQ-801]

### PR DESCRIPTION
**Pull request by njblore**
## Description

Music year: 2020

- Update hero images in sanity for pupils and curriculum
- Add hero image for AI
- Update tab icon for Ai to waving robot
- Update copy for keystage selector on teachers' tab

## How to test

1. Go to https://deploy-preview-2414--oak-web-application.netlify.thenational.academy
2. Click on AI tab
3. You should see an illustration, a new robot icon
4. The curriculum and pupils images should have a thicker border matching the teachers tab (this change was done via sanity so it already is on production)
5. Keystage selector text should be updated on the teachers tab but unchanged in the subject listing page

## Screenshots

How it used to look (delete if n/a):  
Screenshot 2024-05-09 at 08 27 20
Screenshot 2024-05-09 at 08 33 59

How it should now look:  
Screenshot 2024-05-09 at 08 26 46
Screenshot 2024-05-09 at 08 34 11

## ACs

- [x]  Update images in the top area to have consistent border thickness (currently the first one is thicker than others)
- [x]  Replace AI icon in the tabs to use a robot
- [x]  Add an illustration for AI area.
- [x]  Update copy for the Key Stage selector to “ View subjects by key stage”

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
How I have missed being really picky with front end changes :D 

- The AI hero image has been cut off on the right hand side
Screenshot 2024-05-09 at 08 53 37
- The curriculum image is slightly smaller than the other two, not sure if that is intended, just a SLIGHT inconsistency between the tabs that I am sure no one cares about
- The distant between "view subjects by key stage" and the buttons underneath isn't the achieved the same was as it is in Figma (on the site it is 16px to the button, in Fimga it is 16px to the brush boarder). It was like this before this PR, don't think it is worth fixing.

**Comment by njblore** [comment]
@jack-skerrett-oak whoops didn't see that image cropping in my browser! should be fixed now. The spacing between the keystage text I think looks smaller because the brush borders aren't taken into account, it does look squashed though so I could up the spacing a bit? (it's at 16px already)

**Comment by jack-skerrett-oak** [comment]
> @jack-skerrett-oak whoops didn't see that image cropping in my browser! should be fixed now. The spacing between the keystage text I think looks smaller because the brush borders aren't taken into account, it does look squashed though so I could up the spacing a bit? (it's at 16px already)

@njblore I want those brush borders gone entirely at some point, so maybe we just leave it as is and use it as another reason to do that eventually. No one has complained so far :D

**Review by jack-skerrett-oak — APPROVED** [review]

**Review by Monika-Koziol — CHANGES_REQUESTED** [review]
One small change. `Key stage` should be two words.

**Review by Monika-Koziol — APPROVED** [review]

**Pull request merged**
