### PR TITLE
feat: terms and conditions for onboarding [LESQ-1001]

### PR DESCRIPTION
**Pull request by njblore**
## Description

Music year: 1985

- adds text section with links to ts&cs
- slightly refactor school input so it doesn't start in an error state
- added additional tests and also noticed some act errors in onboarding page tests, not sure how I missed that but fixed them (there's some async actions in react-form that causes these so we have to await/find everything) 

## How to test

1. Go to https://deploy-preview-2665--oak-web-application.netlify.thenational.academy/onboarding (feature flag must be active for your distinct id)
3. You should see text below the form for oak's ts & cs and a link to contact us

## Screenshots

How it should now look:
Screenshot 2024-08-05 at 11 57 52

## Checklist

- [ ] school picker still works as expected and highlights error state / disables continue button
- [ ] links in text go to the correct places
- [ ] before merging: check feature flag is not enabled on prod except for specific user ids

### CODE REVIEW

**Review by carlmw — APPROVED** [review]
🚀

**Review by RBrownsett — COMMENTED** [review]
@njblore looks good to me - links work as expected. Just a small thing the design on the ticket does not have full stops after each of the links. Not sure if that was intentional @Monika-Koziol ?

PR Version:

image

Design

image

**Comment by njblore** [comment]
thanks @RBrownsett should have said that these designs/copy aren't finalised as we're just getting the structure and functionality of the onboarding page set up!

**Review by RBrownsett — APPROVED** [review]
Approved - tested with no issues

**Pull request merged**
