### PR TITLE
Feat/pupil 682/style year listing page b

### PR DESCRIPTION
**Pull request by kimon-satan**
### Job Story

**When** I view the YearListingPage,
**I want to see all the oak styles and components**
**So that the UX is high quality**.

### Testing 

https://deploy-preview-2423--oak-web-application.netlify.thenational.academy/pupils/beta/years

### Acceptance criteria

- [x]  page matches designs
- [x] navigates to correct pages
- [x]  keyboard navigation
- [x]  screen reader
- [x]  mobile and tablet
- [x]  passing tests

#### before
image

#### after
image

### CODE REVIEW

**Review by messmike — APPROVED** [review]
lovely stuff, thanks

**Comment by RBrownsett** [comment]
@kimon-satan I'm getting aria role not appropriate warning for the year link buttons when running the accessibility checker

Its odd because the list role has been used and each button has a listitem role attached. I've checked with a screen reader and it does read it correctly but I noticed that the buttons are in fact groups? Might not be a big issue but I thought I would flag it to see if you had any ideas

Accessibilty Insights:

image

Chrome Dev Tools:

image

**Review by RBrownsett — APPROVED** [review]
Moving the the list role to the outer most element fixed the a11y issue. Tested functionality for each year, works as expected. Detailed notes on the Notion Ticket.

**Pull request merged**
