### PR TITLE
Feat/lesq 1108/canonical share page [LESQ-1108]

### PR DESCRIPTION
**Pull request by njblore**
## Description

Music year: {owa_music_year}

- Create canonical share page
- Update lesson share query to accomodate canonical pages
- Refactor helper functions to be shared
- Fix fallback icon on canonical lesson pages when subject can't be determined (eg Combined Science/Biology)

## Issue(s)

Fixes #
Share links from canonical pages with multiple conflating programme factors 404ing

## How to test

1. Go to https://deploy-preview-2880--oak-web-application.netlify.thenational.academy/teachers/lessons/cells
2. Click on Share activities with pupils
3. You should be directed to the Share page
4. Check the non-canonical pages are still working properly
5. Check optionality lesson pages are still working properly
6. Check downloads pages are still working properly

## Screenshots

How it used to look (delete if n/a):
Screenshot 2024-10-14 at 10 08 47
Screenshot 2024-10-14 at 10 08 59

How it should now look:
{screenshots}
Screenshot 2024-10-14 at 10 08 38
Screenshot 2024-10-14 at 10 09 09

## Checklist

- [ ] Lesson share links for KS4 science and maths subjects direct you to the canonical share page
- [ ] Non-canonical share pages still work
- [ ] Fallback icon is 'books' and not 'error' on canonical pages

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]

**Comment by njblore** [comment]
@rightsaidjames I'm not 100% sure why some pages were redirecting to the non canonical share page, but I noticed it happens with download as well so enforced that both should direct to the canonical versions of those pages

**Review by rightsaidjames — APPROVED** [review]
@njblore Good news and bad news...

On the plus side, I'm now getting canonical share and download pages in all the places I've tried 🎉 

However, I tried a [canonical example](https://deploy-preview-2880--oak-web-application.netlify.thenational.academy/teachers/lessons/chapter-1-mr-utterson) and, while the share and download functionality works fine on those pages, the breadcrumbs are wrong because they reference the null variant of each unit instead of (one of) the optionality variants, and it looks like the teacher experience no longer serves up [unit](https://www.thenational.academy/teachers/programmes/english-secondary-ks4-eduqas/units/nineteenth-century-text-first-study/lessons) or [lesson](https://www.thenational.academy/teachers/programmes/english-secondary-ks4-eduqas/units/nineteenth-century-text-first-study/lessons/chapter-1-mr-utterson) pages for the null variant of optionality units.

**Comment by njblore** [comment]
@rightsaidjames aha we were incorrectly pulling in the null unit variant slug from the data when building out the pathways, good catch! fixed that so I think that should be everything canonicalised now, breadcrumbs should remain on the canonical lesson navigating back and forth and will go back into a valid unit from lesson/share/download pages 🤞

**Pull request merged**
