### PR TITLE
Exclude "all" from subject categories in english primary/secondary

### PR DESCRIPTION
**Pull request by orangemug**
## Description
This PR adds to our "fake exclusion table" exclusions for subject categories

```js
{
  subjectcategories: {
    all_disabled: true,
    default_category_id: 19,
  },
}
```

## Issue(s)

Fixes `CUR-830`

## How to test
Cycle 2 (**not enabled**)
1. Go to https://deploy-preview-2950--oak-web-application.netlify.thenational.academy
2. Navigate to the curriculum visualiser english
3. Nothing should have changed, no regressions

Cycle 2 (**is enabled**)

1. Go to https://deploy-preview-2950--oak-web-application.netlify.thenational.academy
2. Navigate to the curriculum visualiser english
3. The "All" subject category should no longer be present

### Screenshots
Before

Screenshot 2024-10-31 at 16 42 52

After

Screenshot 2024-10-31 at 16 42 59

### CODE REVIEW

**Review by rightsaidjames — CHANGES_REQUESTED** [review]
@orangemug Looks good for English Primary, but the page crashes on English Secondary:
http://localhost:3000/teachers/curriculum/english-secondary-aqa/units

```
Error: Error serializing `.curriculumUnitsFormattedData.initialYearSelection["7"].subjectCategory` returned from `getStaticProps` in "/teachers/curriculum/[subjectPhaseSlug]/[tab]".
Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.
```

I think this is because years 7-9 don't have subject categories, and the code is expecting that they do?

Screenshot 2024-11-04 at 15 08 52

**Comment by orangemug** [comment]
@rightsaidjames this looks fine to me, see https://deploy-preview-2950--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-secondary-aqa/units

Any ideas?

**Comment by rightsaidjames** [comment]
@orangemug did you test locally with the cycle 2 flag enabled?

**Comment by orangemug** [comment]
Ah, cycle 2 flag enabled, hopefully fixed in  https://github.com/oaknational/Oak-Web-Application/pull/2950/commits/c1831d692ff1aa5b0f03169dc3f975a4828867e2

**Review by assadk88 — APPROVED** [review]
LGTM 👍

**Review by rightsaidjames — APPROVED** [review]
Looks good! Works for Primary and Secondary English, other lots with (and without) subject categories work as they did before.

**Pull request merged**
