### PR TITLE
[CUR-287] updated partner image to square and added responsive sizing to partner card

### PR DESCRIPTION
**Pull request by sonalisin**
## Description

- Changes the partner image from circular to square
- Updated flex direction from row to column for mobile view
- Updated spacing underneath the partner card

## How to test

1. Go to https://deploy-preview-1945--oak-web-application.netlify.thenational.academy
2. Click on any subject phase combination and scroll to the partner information
3. You should see an updated image for the partner and spacing 

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-09-27 at 17 21 30

How it should now look:
{screenshots
Screenshot 2023-09-27 at 17 20 34

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]
LGTM ✅

**Comment by rightsaidjames** [comment]
Looking good on Desktop and Tablet:
Screenshot 2023-09-28 at 10 21 55
Screenshot 2023-09-28 at 10 22 30
Screenshot 2023-09-28 at 10 22 41

**Review by rightsaidjames — CHANGES_REQUESTED** [review]
But, as shown in Figma, the image should be horizontally centred within the component on mobile:
https://www.figma.com/file/3cz9fb0ObFDLv1c212OtJv/High-fidelity-designs?type=design&node-id=151%3A19416&mode=dev

Screenshot 2023-09-28 at 10 22 06

Screenshot 2023-09-28 at 10 25 42

**Review by rightsaidjames — APPROVED** [review]
Looks good. I can confirm that the spacing between the last component and the footer (caused by lesson squad changes) has also been fixed as part of this PR.

**Pull request merged**
