### PR TITLE
[CUR-326] Feat/unit modal navigates to unit

### PR DESCRIPTION
**Pull request by sonalisin**
## Description

Music year: 1970

- Removed coming soon tag on unit modal when lesson is available

## How to test

1. Go to https://deploy-preview-2142--oak-web-application.netlify.thenational.academy/teachers/curriculum/english-primary/units
2. Click on Simple Sentences
3. You should see the button to take you to the unit. This should redirect to the correct unit listing page
4. Unit optionality modals should have no button or tag
5. Remaining unit modals should have a coming soon label alongside the unit info button

## Screenshots

How it used to look (delete if n/a):
Screenshot 2023-12-21 at 12 09 16

How it should now look:
Screenshot 2023-12-21 at 12 08 22

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by HelenHarlow — COMMENTED** [review]
Looks great! Two things from me:

- Could we make the colour of the text link black (222222)? The current colour (575757) is what we're using for disabled buttons
- When I click to 'see lessons in unit' and then click back in browser, it takes me to the curriculum visualiser without the modal open. Would it be possible to take the user back to that page with the modal open? Hopefully that makes sense

Cheers!

**Comment by sonalisin** [comment]
> Looks great! Two things from me:
> 
> * Could we make the colour of the text link black (222222)? The current colour (575757) is what we're using for disabled buttons
> * When I click to 'see lessons in unit' and then click back in browser, it takes me to the curriculum visualiser without the modal open. Would it be possible to take the user back to that page with the modal open? Hopefully that makes sense
> 
> Cheers!

Updated the font colour - the modal being open to a specific page on return may be out of scope for this ticket but a new ticket to add the unit modal to the URL structure would prove useful in the future.

**Comment by rightsaidjames** [comment]
@sonalisin From [/teachers/curriculum/science-secondary-aqa/units](https://deploy-preview-2142--oak-web-application.netlify.thenational.academy/teachers/curriculum/science-secondary-aqa/units) (or any exam board), if you select the Year 10 unit `Measuring waves` the URL points to [/teachers/programmes/combined-science-secondary-ks4/units/measuring-waves/lessons](https://deploy-preview-2142--oak-web-application.netlify.thenational.academy/teachers/programmes/combined-science-secondary-ks4/units/measuring-waves/lessons) which is a 404, because the slug doesn't include an exam board or a tier.

Screenshot 2024-01-09 at 17 05 11

Screenshot 2024-01-09 at 17 05 25

Same issue with Y10 Maths:
[/teachers/curriculum/maths-secondary/units](https://deploy-preview-2142--oak-web-application.netlify.thenational.academy/teachers/curriculum/maths-secondary/units)

The `Surds` modal links through to [/teachers/programmes/maths-secondary-ks4/units/surds/lessons](https://deploy-preview-2142--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4/units/surds/lessons) regardless of the tier selected.

Screenshot 2024-01-09 at 17 09 54

**Comment by rightsaidjames** [comment]
Another thing to consider @sonalisin - we won't have published units with options until the 15th January, but perhaps there could be a Jest test for this to make sure the sub-modals are linking through to the right unit option?

**Review by lioneljingles — APPROVED** [review]

**Comment by rightsaidjames** [comment]
I've now confirmed that clickable links for units with optionality are present and have the correct URLs (taking exam board and selected unit option into account):
Screenshot 2024-01-17 at 16 59 51
Screenshot 2024-01-17 at 17 01 40
(Year 10 English, AQA, Unit 1, select either of the unit options)

Screenshot 2024-01-17 at 17 02 39
Screenshot 2024-01-17 at 17 02 50
(Year 11 English, Edexcel, Unit 3, select either of the unit options)

Simpler units with optionality are also working as expected:
Screenshot 2024-01-17 at 17 06 49
(Year 2, unit 7, either option)

I have also confirmed that tiers, child subjects and exam boards are working as before. My test cases for this are Y10 Maths (Surds) and Y10 Combined Science/Physics (Measuring waves). No optionality is involved for Science and Maths at this point, in terms of units with published lessons.

**Review by rightsaidjames — APPROVED** [review]

**Review by lioneljingles — APPROVED** [review]

**Pull request merged**
