### PR TITLE
LESQ-715: Fix specialist heading icon sizes

### PR DESCRIPTION
**Pull request by k-huggs**
## Description

Music year: 2014
https://www.youtube.com/watch?v=ZbZSe6N_BXs

- Amends heading Icon sizes on `SpecialistProgrammeHeadingListing` and `HeaderListing` components

## Issue(s)

Fixes #LESQ-715

## Screenshots

How it used to look (delete if n/a):
Screenshot 2024-03-26 at 08 41 51

Screenshot 2024-03-20 at 10 38 02

How it should now look:
Screenshot 2024-03-26 at 08 39 01
Screenshot 2024-03-26 at 08 40 16
Screenshot 2024-03-26 at 08 40 54

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by njblore** [comment]
can we add some screenshots as we can't see in preview?

**Review by JBR90 — APPROVED** [review]
Looks good to me, does this match figma sizes ? This will effect all subject icons, might be worth getting a design review as well.

**Review by jack-skerrett-oak — COMMENTED** [review]
The image sizes on the unit/lesson listing pages have gotten smaller. As Joe says, probably good to get Nirav/Monika's input

Screenshot 2024-03-26 at 09 57 41
Screenshot 2024-03-26 at 09 57 43

**Review by narvinda — APPROVED** [review]

**Review by jack-skerrett-oak — APPROVED** [review]
Nirav has said yes!

**Pull request merged**
