### PR TITLE
Invalid value for `w:beforeAutospacing` in docx

### PR DESCRIPTION
**Pull request by orangemug**
## Description
Fixes for docx validation errors and also visual issues with level 6 headings.

## Issue(s)

Fixes `CUR-1153`

## How to test

1. Go to https://deploy-preview-3070--oak-web-application.netlify.thenational.academy/teachers/curriculum/
2. From the picker "English secondary (AQA)"
3. Download docment
4. Level 6 heading should be correctly spaced.

## Screenshots
Before
Screenshot 2024-12-16 at 16 19 02

After
Screenshot 2024-12-16 at 16 18 48

### CODE REVIEW

**Comment by orangemug** [comment]
@HelenHarlow can you confirm the visual changes?

**Review by HelenHarlow — APPROVED** [review]
Looks good to me!

**Comment by sonalisin** [comment]
Have tested this @rightsaidjames and looks good to me!

**Review by sonalisin — APPROVED** [review]

**Pull request merged**
