### PR TITLE
Retire/early release page - LESQ-509

### PR DESCRIPTION
**Pull request by JBR90**
## Description

Music year: 1972

Now more new lessons are coming online, we no longer need a dedicated page for early release units. 

- [x]  Remove from hamburger
- [x]  Remove from curriculum pages tab
- [x]  Remove the page

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2169--oak-web-application.netlify.thenational.academy/teachers/early-release-units

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Review by njblore — APPROVED** [review]
Looks good, have we asked platform team to add a redirect as well?

**Comment by JBR90** [comment]
> Looks good, have we asked platform team to add a redirect as well?

Yes Jim said he can do this for us today.

**Review by jack-skerrett-oak — APPROVED** [review]
The page is no more!

**Pull request merged**
