### PR TITLE
[LESQ-42] feat: add mv-lesson-listing to curriculum api 2023

### PR DESCRIPTION
**Pull request by mantagen**
## Description

- adds `lessonListing.gql`
- adds lessonListing to curriculum api 2023
- updates some types to use new lesson listing types

## How to test

1. Go to {cloud link}
2. Go to `/beta/teachers-2023/programmes/physics-secondary-ks4/units/measuring-and-calculating-motion/lessons`
3. You should get a bunch of lesson from that prg/unit!

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by JBR90 — APPROVED** [review]
Looks good and works as expected

**Review by jack-skerrett-oak — APPROVED** [review]
I'm assuming there are no graphics explaining what content is in the lesson because we don't currently have lesson resources in the data the MVs are pointing at?

**Comment by mantagen** [comment]
> I'm assuming there are no graphics explaining what content is in the lesson because we don't currently have lesson resources in the data the MVs are pointing at?

@jack-skerrett-oak yep more or less. This is the case for presentations, worksheets, videos (all of which the 2023 model doesn't support just yet to my knowledge). We can however add the Quizzes graphic where appropriate. Will add it in a supplementary PR as it will require an MV change too

**Comment by jack-skerrett-oak** [comment]
> > I'm assuming there are no graphics explaining what content is in the lesson because we don't currently have lesson resources in the data the MVs are pointing at?
> 
> @jack-skerrett-oak yep more or less. This is the case for presentations, worksheets, videos (all of which the 2023 model doesn't support just yet to my knowledge). We can however add the Quizzes graphic where appropriate. Will add it in a supplementary PR as it will require an MV change too

@mantagen Ah OK, I had assumed that was part of the original lesson listing MV work to get it to match current spec

**Comment by mantagen** [comment]
>@mantagen Ah OK, I had assumed that was part of the original lesson listing MV work to get it to match current spec

Where possible, yes

**Pull request merged**
