### PR TITLE
feat: add links for terms and conditions; and OGL license to DocX template

### PR DESCRIPTION
**Pull request by assadk88**
## Description

Music year: {owa_music_year}

- List of changes

## Issue(s)

Fixes #[859](https://www.notion.so/oaknationalacademy/Add-hyperlinks-to-OGL-and-Oak-s-T-Cs-to-the-docx-d508bff9dd8241ba8919dbbe0640bf6b?pvs=4)

## How to test

1. Go to https://deploy-preview-3049--oak-web-application.netlify.thenational.academy
2. Navigate to the Download tab of a curriculum
3. Download a curriculum plan
4. Open the downloaded curriculum plan `.docx` file and navigate to the last page of the document

## Screenshots

How it used to look (delete if n/a):
image

How it should now look:
image

## Checklist

- [ ] ~~Added or updated tests where appropriate~~
- [X] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [X] Design sign-off
- [X] Approved by product owner
- [ ] ~~Does this PR update a package with a breaking change~~

### CODE REVIEW

**Comment by orangemug** [comment]
@assadk88 when I download the document I see a missing space before the links, see
Screenshot 2024-12-03 at 14 25 04

**Comment by orangemug** [comment]
Screenshot 2024-12-03 at 14 32 37

Is fixed with

```diff
+++ b/src/pages-helpers/curriculum/docx/builder/11_backCover.ts
@@ -182,7 +182,7 @@ export default async function generate(
             <w:color w:val="222222" />
             <w:sz w:val="24" />
           </w:rPr>
-          <w:t>Licensed on the </w:t>
+          <w:t xml:space="preserve">Licensed on the </w:t>
         </w:r>
         ${wrapInLinkTo(
           links.ogl,
@@ -219,7 +219,7 @@ export default async function generate(
             <w:color w:val="222222" />
             <w:sz w:val="24" />
           </w:rPr>
-          <w:t>, except where otherwise stated. See </w:t>
+          <w:t xml:space="preserve">, except where otherwise stated. See </w:t>
         </w:r>
         ${wrapInLinkTo(
           links.terms,

```

**Review by orangemug — APPROVED** [review]
I've approved the PR because code is all good (apart from adding the  `xml:space="preserve"`)

Once that's fixed @rightsaidjames can QA.

**Review by rightsaidjames — APPROVED** [review]
Looks good - links work as they should, appearance is consistent in Word (Mac), Google Docs, LibreOffice, Word (web-based) and Pages.

Cross-comparison of Word (Mac), Google Docs and Pages:
Screenshot 2024-12-03 at 15 11 42

Word (web-based):
Screenshot 2024-12-03 at 15 19 08

Pages:
Screenshot 2024-12-03 at 15 21 42

**Pull request merged**
