### PR TITLE
feat(video): create standalone video page

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

Music year: 2012

- List of changes

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-2456--oak-web-application.netlify.thenational.academy/videos/mgQ9kDg302EyPWi5aKh00hTgLy9xwG2ud8U82R9uVw68M/player
2. Click on the play button
3. You should see videos working for correct playback ids

### Job Story

**When** a commercial partner uses an oak video,
**I want the to use a none branded mux video player page**
**So that use can** use oak video assets on different applications.

### Implementation details

serve from /api/videos/[videoId]/player

Use the existing mux player and just feed in the muxId

### Acceptance criteria

- [x]  plays video with correct id
- [x]  provides suitable information for an incorrect id

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner
- [ ] Does this PR update a package with a breaking change

### CODE REVIEW

**Comment by BTitterington** [comment]
There is scrolling on the page for me, is that okay? Or should it fit the viewport?

**Comment by aakeshp** [comment]
As per our slack; it would be great if we removed the help button and also if the URL was /api/videos/player/[videoId]/.

**Review by aakeshp — APPROVED** [review]
From a product point of view this is great.

**Review by BTitterington — APPROVED** [review]

**Pull request merged**
