### PR TITLE
LESQ-36 feat(unit-listing): add optionality options to the unit listing page

### PR DESCRIPTION
**Pull request by benprotheroe**
## Description

display optionality units on unit listing page

## Issue(s)

Fixes #

## How to test

1. Go to https://deploy-preview-1741--oak-web-application.netlify.thenational.academy/beta/teachers-2023/programmes/english-secondary-aqa/units
2. Click on _______
3. You should see different optionality units displayed

## Screenshots

How it used to look (delete if n/a):
{screenshots}

How it should now look:
{screenshots}

## Checklist

- [ ] Added or updated tests where appropriate
- [ ] Manually tested across browsers / devices
- [ ] Considered impact on accessibility
- [ ] Design sign-off
- [ ] Approved by product owner

### CODE REVIEW

**Review by k-huggs — APPROVED** [review]
LGTM

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
On the ticket we had talked about displaying the options under the unit title. Is that still possible? So unit title: option1, option2, option3 as per the rubbish sketch I did :D 

Also just FYI, the programme slug in your link is missing a key stage and the page doesn't load.

**Review by jack-skerrett-oak — APPROVED** [review]
Let's get it in so you can work on that other one!

**Pull request merged**
