### PR TITLE
Feat/lesq 242/lesson header update [LESQ-242]

### PR DESCRIPTION
**Pull request by njblore**
## Description

- Added a new component `HeaderMetadata` to display the extra data in lesson listing header
- Updated graphql queries with the updated schema

## How to test

1. Go to https://deploy-preview-1955--oak-web-application.netlify.thenational.academy/teachers/programmes/maths-secondary-ks4-foundation/units/surds/lessons
2. You should see the year and tier in the header

## Screenshots

How it should now look:
Screenshot 2023-09-29 at 13 23 38
Screenshot 2023-09-29 at 13 22 14
Screenshot 2023-09-29 at 14 00 22

## Checklist

- [ ]  A lesson listing page should show the year group a unit belongs to in the header
- [ ]  A lesson listing page should show the tier and exam board a unit belongs to IF it has a tier and exam board

### CODE REVIEW

**Comment by verityroberts** [comment]
For testing - Physics KS4 has examboard and tier

**Review by JBR90 — APPROVED** [review]
LGTM

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Tiny change, could "aria-hidden" or something to that effect (I never know the right one) be added to the bullet point element, currently you can get the screen reader to read it and it adds no additional context. Looks good other than that.

**Review by jack-skerrett-oak — APPROVED** [review]

**Pull request merged**
