### PR TITLE
ENG-492 fix: legacy canonical lesson + downloads

### PR DESCRIPTION
**Pull request by mantagen**
## Description

- Canonical lesson/download pages are currently 404ing. They aren’t currently linked to anywhere so it’s not urgent urgent, but should be fixed.

**Note:** when a canonical lesson has only one lesson pathway, the download links go the "in pathway" version of lesson downloads. If this is not desired, should ticket

## How to test

1. Go to https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/introduction-to-epic-poetry-68u3gc
2. should not 404
3. Go https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/introduction-to-epic-poetry-68u3gc/downloads
4. should not 404
5. should be no regressions of non-legacy content

### CODE REVIEW

**Review by jack-skerrett-oak — COMMENTED** [review]
I am only going to comment as I don't know if I will be around to re-approve!

There is some difference in the navigation links between how a canonical lesson for the old content renders vs new content. 

1. On a lesson that appears in multiple units in the new content, the breadcrumb is shortened to just show the key stage the lesson is in rather than the whole breadcrumb: https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/transverse-waves but for a similar lesson in the old content, it shows the whole breadcrumb (in this example it defaults to the "higher" programme being selected https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/add-two-column-vectors-including-diagrams-to-give-a-resultant-vector-6xgp2d)

2. On this lesson https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/add-two-column-vectors-including-diagrams-to-give-a-resultant-vector-6xgp2d (again), at the bottom where it shows the unit, it lists three units to pick from with no clear distinction between them. These are the 3 different tiers this unit exists in (foundation core and higher). We handle this nicely for new content (See that same transverse waves lesson)

**Review by rightsaidjames — COMMENTED** [review]
@mantagen Can you update the branch against main, as there are is a good amount of changes that have come in since this PR was last updated.

Also Jack's comments above still apply, but I don't know enough about how this stuff works to be able to tell you if it should block merge.

**Comment by mantagen** [comment]
Thanks @rightsaidjames . cc @jack-skerrett-oak 

As I see it:
1. is by design, it's how the canonical page currently behaves for new content, we can change, but as a separate piece of work
2. i see what the issue is here, it's that in [data-tools](https://github.com/oaknational/data-tools), the mv_lessons (which this page consumes) does not contain tier information. So what needs to happen is the following:
  -  add tier information (tier_slug, tier_title) to mv_lessons_6 in data-tools. This does not require hard rewiring, just needs to be included in the SELECT, a simple task
  - (tier_slug, tier_title) need to be added to `src/node-lib/curriculum-api/queries/lessonOverviewCanonical.gql`

I won't be able to finish this before I go away, but I'll add it to a (short) docs of leftovers I'm leaving behind.

**Review by jack-skerrett-oak — CHANGES_REQUESTED** [review]
Sorry, found another edge case now I'm looking again! The links at the bottom seem fine now though!

- This canonical lesson (https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/prokaryotic-and-eukaryotic-cells-b9qqye) is correctly linked at the bottom. However, the breadcrumb shows the canonical lesson belonging to combined science. In instances where a lesson appears in multiple places, we have been removing parts of the breadcrumb, see here for new content  (https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/transverse-waves#exit-quiz) and here for an example in the old content (https://deploy-preview-2011--oak-web-application.netlify.thenational.academy/teachers/lessons/adding-directed-numbers-chjk4t)

**Review by jack-skerrett-oak — APPROVED** [review]
Agreed this PR has been open for too long, we have written the small issue up as a bug to fix another time (it may also not be an issue post migration if this takes that long https://www.notion.so/oaknationalacademy/Some-canonical-lessons-have-the-incorrect-breadcrumb-485c699079764541b4186f7a8f998679?pvs=4)

**Pull request merged**
